/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Late.Client;
using Late.Model;

namespace Late.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContactsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Bulk create contacts
        /// </summary>
        /// <remarks>
        /// Import up to 1000 contacts at a time. Skips duplicates.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <returns>BulkCreateContacts200Response</returns>
        BulkCreateContacts200Response BulkCreateContacts(BulkCreateContactsRequest bulkCreateContactsRequest);

        /// <summary>
        /// Bulk create contacts
        /// </summary>
        /// <remarks>
        /// Import up to 1000 contacts at a time. Skips duplicates.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <returns>ApiResponse of BulkCreateContacts200Response</returns>
        ApiResponse<BulkCreateContacts200Response> BulkCreateContactsWithHttpInfo(BulkCreateContactsRequest bulkCreateContactsRequest);
        /// <summary>
        /// Create contact
        /// </summary>
        /// <remarks>
        /// Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <returns>CreateContact200Response</returns>
        CreateContact200Response CreateContact(CreateContactRequest createContactRequest);

        /// <summary>
        /// Create contact
        /// </summary>
        /// <remarks>
        /// Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <returns>ApiResponse of CreateContact200Response</returns>
        ApiResponse<CreateContact200Response> CreateContactWithHttpInfo(CreateContactRequest createContactRequest);
        /// <summary>
        /// Delete contact
        /// </summary>
        /// <remarks>
        /// Permanently deletes a contact and all associated channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns></returns>
        void DeleteContact(string contactId);

        /// <summary>
        /// Delete contact
        /// </summary>
        /// <remarks>
        /// Permanently deletes a contact and all associated channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteContactWithHttpInfo(string contactId);
        /// <summary>
        /// Get contact
        /// </summary>
        /// <remarks>
        /// Returns a contact with all associated messaging channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>GetContact200Response</returns>
        GetContact200Response GetContact(string contactId);

        /// <summary>
        /// Get contact
        /// </summary>
        /// <remarks>
        /// Returns a contact with all associated messaging channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>ApiResponse of GetContact200Response</returns>
        ApiResponse<GetContact200Response> GetContactWithHttpInfo(string contactId);
        /// <summary>
        /// List channels for a contact
        /// </summary>
        /// <remarks>
        /// Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>GetContactChannels200Response</returns>
        GetContactChannels200Response GetContactChannels(string contactId);

        /// <summary>
        /// List channels for a contact
        /// </summary>
        /// <remarks>
        /// Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>ApiResponse of GetContactChannels200Response</returns>
        ApiResponse<GetContactChannels200Response> GetContactChannelsWithHttpInfo(string contactId);
        /// <summary>
        /// List contacts
        /// </summary>
        /// <remarks>
        /// List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>ListContacts200Response</returns>
        ListContacts200Response ListContacts(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default);

        /// <summary>
        /// List contacts
        /// </summary>
        /// <remarks>
        /// List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>ApiResponse of ListContacts200Response</returns>
        ApiResponse<ListContacts200Response> ListContactsWithHttpInfo(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default);
        /// <summary>
        /// Update contact
        /// </summary>
        /// <remarks>
        /// Update one or more fields on a contact. Only provided fields are changed.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <returns>UpdateContact200Response</returns>
        UpdateContact200Response UpdateContact(string contactId, UpdateContactRequest? updateContactRequest = default);

        /// <summary>
        /// Update contact
        /// </summary>
        /// <remarks>
        /// Update one or more fields on a contact. Only provided fields are changed.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <returns>ApiResponse of UpdateContact200Response</returns>
        ApiResponse<UpdateContact200Response> UpdateContactWithHttpInfo(string contactId, UpdateContactRequest? updateContactRequest = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContactsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Bulk create contacts
        /// </summary>
        /// <remarks>
        /// Import up to 1000 contacts at a time. Skips duplicates.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BulkCreateContacts200Response</returns>
        System.Threading.Tasks.Task<BulkCreateContacts200Response> BulkCreateContactsAsync(BulkCreateContactsRequest bulkCreateContactsRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Bulk create contacts
        /// </summary>
        /// <remarks>
        /// Import up to 1000 contacts at a time. Skips duplicates.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BulkCreateContacts200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<BulkCreateContacts200Response>> BulkCreateContactsWithHttpInfoAsync(BulkCreateContactsRequest bulkCreateContactsRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create contact
        /// </summary>
        /// <remarks>
        /// Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateContact200Response</returns>
        System.Threading.Tasks.Task<CreateContact200Response> CreateContactAsync(CreateContactRequest createContactRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create contact
        /// </summary>
        /// <remarks>
        /// Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateContact200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateContact200Response>> CreateContactWithHttpInfoAsync(CreateContactRequest createContactRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete contact
        /// </summary>
        /// <remarks>
        /// Permanently deletes a contact and all associated channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteContactAsync(string contactId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete contact
        /// </summary>
        /// <remarks>
        /// Permanently deletes a contact and all associated channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteContactWithHttpInfoAsync(string contactId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get contact
        /// </summary>
        /// <remarks>
        /// Returns a contact with all associated messaging channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetContact200Response</returns>
        System.Threading.Tasks.Task<GetContact200Response> GetContactAsync(string contactId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get contact
        /// </summary>
        /// <remarks>
        /// Returns a contact with all associated messaging channels.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetContact200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetContact200Response>> GetContactWithHttpInfoAsync(string contactId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List channels for a contact
        /// </summary>
        /// <remarks>
        /// Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetContactChannels200Response</returns>
        System.Threading.Tasks.Task<GetContactChannels200Response> GetContactChannelsAsync(string contactId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List channels for a contact
        /// </summary>
        /// <remarks>
        /// Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetContactChannels200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetContactChannels200Response>> GetContactChannelsWithHttpInfoAsync(string contactId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List contacts
        /// </summary>
        /// <remarks>
        /// List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListContacts200Response</returns>
        System.Threading.Tasks.Task<ListContacts200Response> ListContactsAsync(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List contacts
        /// </summary>
        /// <remarks>
        /// List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListContacts200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListContacts200Response>> ListContactsWithHttpInfoAsync(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update contact
        /// </summary>
        /// <remarks>
        /// Update one or more fields on a contact. Only provided fields are changed.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateContact200Response</returns>
        System.Threading.Tasks.Task<UpdateContact200Response> UpdateContactAsync(string contactId, UpdateContactRequest? updateContactRequest = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update contact
        /// </summary>
        /// <remarks>
        /// Update one or more fields on a contact. Only provided fields are changed.
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateContact200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateContact200Response>> UpdateContactWithHttpInfoAsync(string contactId, UpdateContactRequest? updateContactRequest = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContactsApi : IContactsApiSync, IContactsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ContactsApi : IDisposable, IContactsApi
    {
        private Late.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ContactsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ContactsApi(string basePath)
        {
            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                new Late.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Late.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ContactsApi(Late.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Late.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ContactsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ContactsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                new Late.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Late.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ContactsApi(HttpClient client, Late.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Late.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ContactsApi(Late.Client.ISynchronousClient client, Late.Client.IAsynchronousClient asyncClient, Late.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Late.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Late.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Late.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Late.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Late.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Bulk create contacts Import up to 1000 contacts at a time. Skips duplicates.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <returns>BulkCreateContacts200Response</returns>
        public BulkCreateContacts200Response BulkCreateContacts(BulkCreateContactsRequest bulkCreateContactsRequest)
        {
            Late.Client.ApiResponse<BulkCreateContacts200Response> localVarResponse = BulkCreateContactsWithHttpInfo(bulkCreateContactsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Bulk create contacts Import up to 1000 contacts at a time. Skips duplicates.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <returns>ApiResponse of BulkCreateContacts200Response</returns>
        public Late.Client.ApiResponse<BulkCreateContacts200Response> BulkCreateContactsWithHttpInfo(BulkCreateContactsRequest bulkCreateContactsRequest)
        {
            // verify the required parameter 'bulkCreateContactsRequest' is set
            if (bulkCreateContactsRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'bulkCreateContactsRequest' when calling ContactsApi->BulkCreateContacts");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bulkCreateContactsRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BulkCreateContacts200Response>("/v1/contacts/bulk", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BulkCreateContacts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Bulk create contacts Import up to 1000 contacts at a time. Skips duplicates.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BulkCreateContacts200Response</returns>
        public async System.Threading.Tasks.Task<BulkCreateContacts200Response> BulkCreateContactsAsync(BulkCreateContactsRequest bulkCreateContactsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<BulkCreateContacts200Response> localVarResponse = await BulkCreateContactsWithHttpInfoAsync(bulkCreateContactsRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Bulk create contacts Import up to 1000 contacts at a time. Skips duplicates.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bulkCreateContactsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BulkCreateContacts200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<BulkCreateContacts200Response>> BulkCreateContactsWithHttpInfoAsync(BulkCreateContactsRequest bulkCreateContactsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'bulkCreateContactsRequest' is set
            if (bulkCreateContactsRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'bulkCreateContactsRequest' when calling ContactsApi->BulkCreateContacts");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bulkCreateContactsRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<BulkCreateContacts200Response>("/v1/contacts/bulk", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BulkCreateContacts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create contact Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <returns>CreateContact200Response</returns>
        public CreateContact200Response CreateContact(CreateContactRequest createContactRequest)
        {
            Late.Client.ApiResponse<CreateContact200Response> localVarResponse = CreateContactWithHttpInfo(createContactRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create contact Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <returns>ApiResponse of CreateContact200Response</returns>
        public Late.Client.ApiResponse<CreateContact200Response> CreateContactWithHttpInfo(CreateContactRequest createContactRequest)
        {
            // verify the required parameter 'createContactRequest' is set
            if (createContactRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'createContactRequest' when calling ContactsApi->CreateContact");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createContactRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateContact200Response>("/v1/contacts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create contact Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateContact200Response</returns>
        public async System.Threading.Tasks.Task<CreateContact200Response> CreateContactAsync(CreateContactRequest createContactRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<CreateContact200Response> localVarResponse = await CreateContactWithHttpInfoAsync(createContactRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create contact Create a new contact. Optionally create a platform channel in the same request by providing accountId, platform, and platformIdentifier.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createContactRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateContact200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<CreateContact200Response>> CreateContactWithHttpInfoAsync(CreateContactRequest createContactRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createContactRequest' is set
            if (createContactRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'createContactRequest' when calling ContactsApi->CreateContact");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createContactRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateContact200Response>("/v1/contacts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete contact Permanently deletes a contact and all associated channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns></returns>
        public void DeleteContact(string contactId)
        {
            DeleteContactWithHttpInfo(contactId);
        }

        /// <summary>
        /// Delete contact Permanently deletes a contact and all associated channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Late.Client.ApiResponse<Object> DeleteContactWithHttpInfo(string contactId)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->DeleteContact");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/v1/contacts/{contactId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete contact Permanently deletes a contact and all associated channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteContactAsync(string contactId, System.Threading.CancellationToken cancellationToken = default)
        {
            await DeleteContactWithHttpInfoAsync(contactId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete contact Permanently deletes a contact and all associated channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<Object>> DeleteContactWithHttpInfoAsync(string contactId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->DeleteContact");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/v1/contacts/{contactId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get contact Returns a contact with all associated messaging channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>GetContact200Response</returns>
        public GetContact200Response GetContact(string contactId)
        {
            Late.Client.ApiResponse<GetContact200Response> localVarResponse = GetContactWithHttpInfo(contactId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get contact Returns a contact with all associated messaging channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>ApiResponse of GetContact200Response</returns>
        public Late.Client.ApiResponse<GetContact200Response> GetContactWithHttpInfo(string contactId)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->GetContact");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetContact200Response>("/v1/contacts/{contactId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get contact Returns a contact with all associated messaging channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetContact200Response</returns>
        public async System.Threading.Tasks.Task<GetContact200Response> GetContactAsync(string contactId, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<GetContact200Response> localVarResponse = await GetContactWithHttpInfoAsync(contactId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get contact Returns a contact with all associated messaging channels.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetContact200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<GetContact200Response>> GetContactWithHttpInfoAsync(string contactId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->GetContact");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetContact200Response>("/v1/contacts/{contactId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List channels for a contact Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>GetContactChannels200Response</returns>
        public GetContactChannels200Response GetContactChannels(string contactId)
        {
            Late.Client.ApiResponse<GetContactChannels200Response> localVarResponse = GetContactChannelsWithHttpInfo(contactId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List channels for a contact Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <returns>ApiResponse of GetContactChannels200Response</returns>
        public Late.Client.ApiResponse<GetContactChannels200Response> GetContactChannelsWithHttpInfo(string contactId)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->GetContactChannels");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetContactChannels200Response>("/v1/contacts/{contactId}/channels", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetContactChannels", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List channels for a contact Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetContactChannels200Response</returns>
        public async System.Threading.Tasks.Task<GetContactChannels200Response> GetContactChannelsAsync(string contactId, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<GetContactChannels200Response> localVarResponse = await GetContactChannelsWithHttpInfoAsync(contactId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List channels for a contact Returns all messaging channels linked to a contact (e.g. Instagram DM, Telegram, WhatsApp).
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetContactChannels200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<GetContactChannels200Response>> GetContactChannelsWithHttpInfoAsync(string contactId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->GetContactChannels");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetContactChannels200Response>("/v1/contacts/{contactId}/channels", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetContactChannels", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List contacts List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>ListContacts200Response</returns>
        public ListContacts200Response ListContacts(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default)
        {
            Late.Client.ApiResponse<ListContacts200Response> localVarResponse = ListContactsWithHttpInfo(profileId, search, tag, platform, isSubscribed, limit, skip);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List contacts List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <returns>ApiResponse of ListContacts200Response</returns>
        public Late.Client.ApiResponse<ListContacts200Response> ListContactsWithHttpInfo(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default)
        {
            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (profileId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "profileId", profileId));
            }
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (tag != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "tag", tag));
            }
            if (platform != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "platform", platform));
            }
            if (isSubscribed != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "isSubscribed", isSubscribed));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (skip != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "skip", skip));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListContacts200Response>("/v1/contacts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListContacts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List contacts List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListContacts200Response</returns>
        public async System.Threading.Tasks.Task<ListContacts200Response> ListContactsAsync(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<ListContacts200Response> localVarResponse = await ListContactsWithHttpInfoAsync(profileId, search, tag, platform, isSubscribed, limit, skip, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List contacts List and search contacts for a profile. Supports filtering by tags, platform, subscription status, and full-text search.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId">Filter by profile. Omit to list across all profiles (optional)</param>
        /// <param name="search"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="platform"> (optional)</param>
        /// <param name="isSubscribed"> (optional)</param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="skip"> (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListContacts200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<ListContacts200Response>> ListContactsWithHttpInfoAsync(string? profileId = default, string? search = default, string? tag = default, string? platform = default, string? isSubscribed = default, int? limit = default, int? skip = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (profileId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "profileId", profileId));
            }
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (tag != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "tag", tag));
            }
            if (platform != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "platform", platform));
            }
            if (isSubscribed != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "isSubscribed", isSubscribed));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (skip != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "skip", skip));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListContacts200Response>("/v1/contacts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListContacts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update contact Update one or more fields on a contact. Only provided fields are changed.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <returns>UpdateContact200Response</returns>
        public UpdateContact200Response UpdateContact(string contactId, UpdateContactRequest? updateContactRequest = default)
        {
            Late.Client.ApiResponse<UpdateContact200Response> localVarResponse = UpdateContactWithHttpInfo(contactId, updateContactRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update contact Update one or more fields on a contact. Only provided fields are changed.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <returns>ApiResponse of UpdateContact200Response</returns>
        public Late.Client.ApiResponse<UpdateContact200Response> UpdateContactWithHttpInfo(string contactId, UpdateContactRequest? updateContactRequest = default)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->UpdateContact");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter
            localVarRequestOptions.Data = updateContactRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<UpdateContact200Response>("/v1/contacts/{contactId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update contact Update one or more fields on a contact. Only provided fields are changed.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateContact200Response</returns>
        public async System.Threading.Tasks.Task<UpdateContact200Response> UpdateContactAsync(string contactId, UpdateContactRequest? updateContactRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<UpdateContact200Response> localVarResponse = await UpdateContactWithHttpInfoAsync(contactId, updateContactRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update contact Update one or more fields on a contact. Only provided fields are changed.
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contactId"></param>
        /// <param name="updateContactRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateContact200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<UpdateContact200Response>> UpdateContactWithHttpInfoAsync(string contactId, UpdateContactRequest? updateContactRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'contactId' is set
            if (contactId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'contactId' when calling ContactsApi->UpdateContact");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("contactId", Late.Client.ClientUtils.ParameterToString(contactId)); // path parameter
            localVarRequestOptions.Data = updateContactRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<UpdateContact200Response>("/v1/contacts/{contactId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateContact", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
