/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing AddTrackingTagSharedAccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddTrackingTagSharedAccountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddTrackingTagSharedAccountRequest
        //private AddTrackingTagSharedAccountRequest instance;

        public AddTrackingTagSharedAccountRequestTests()
        {
            // TODO uncomment below to create an instance of AddTrackingTagSharedAccountRequest
            //instance = new AddTrackingTagSharedAccountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddTrackingTagSharedAccountRequest
        /// </summary>
        [Fact]
        public void AddTrackingTagSharedAccountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddTrackingTagSharedAccountRequest
            //Assert.IsType<AddTrackingTagSharedAccountRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AdAccountId'
        /// </summary>
        [Fact]
        public void AdAccountIdTest()
        {
            // TODO unit test for the property 'AdAccountId'
        }
    }
}
