/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing AdjustConversionsRequestAdjustmentsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdjustConversionsRequestAdjustmentsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdjustConversionsRequestAdjustmentsInner
        //private AdjustConversionsRequestAdjustmentsInner instance;

        public AdjustConversionsRequestAdjustmentsInnerTests()
        {
            // TODO uncomment below to create an instance of AdjustConversionsRequestAdjustmentsInner
            //instance = new AdjustConversionsRequestAdjustmentsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdjustConversionsRequestAdjustmentsInner
        /// </summary>
        [Fact]
        public void AdjustConversionsRequestAdjustmentsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdjustConversionsRequestAdjustmentsInner
            //Assert.IsType<AdjustConversionsRequestAdjustmentsInner>(instance);
        }

        /// <summary>
        /// Test the property 'AdjustmentType'
        /// </summary>
        [Fact]
        public void AdjustmentTypeTest()
        {
            // TODO unit test for the property 'AdjustmentType'
        }

        /// <summary>
        /// Test the property 'AdjustmentTime'
        /// </summary>
        [Fact]
        public void AdjustmentTimeTest()
        {
            // TODO unit test for the property 'AdjustmentTime'
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

        /// <summary>
        /// Test the property 'Gclid'
        /// </summary>
        [Fact]
        public void GclidTest()
        {
            // TODO unit test for the property 'Gclid'
        }

        /// <summary>
        /// Test the property 'ConversionTime'
        /// </summary>
        [Fact]
        public void ConversionTimeTest()
        {
            // TODO unit test for the property 'ConversionTime'
        }

        /// <summary>
        /// Test the property 'RestatementValue'
        /// </summary>
        [Fact]
        public void RestatementValueTest()
        {
            // TODO unit test for the property 'RestatementValue'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
    }
}
