/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsListResponsePostsInnerMediaItemsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsListResponsePostsInnerMediaItemsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsListResponsePostsInnerMediaItemsInner
        //private AnalyticsListResponsePostsInnerMediaItemsInner instance;

        public AnalyticsListResponsePostsInnerMediaItemsInnerTests()
        {
            // TODO uncomment below to create an instance of AnalyticsListResponsePostsInnerMediaItemsInner
            //instance = new AnalyticsListResponsePostsInnerMediaItemsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsListResponsePostsInnerMediaItemsInner
        /// </summary>
        [Fact]
        public void AnalyticsListResponsePostsInnerMediaItemsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsListResponsePostsInnerMediaItemsInner
            //Assert.IsType<AnalyticsListResponsePostsInnerMediaItemsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Fact]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }

        /// <summary>
        /// Test the property 'AltText'
        /// </summary>
        [Fact]
        public void AltTextTest()
        {
            // TODO unit test for the property 'AltText'
        }
    }
}
