/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsOverviewDataStaleness
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsOverviewDataStalenessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsOverviewDataStaleness
        //private AnalyticsOverviewDataStaleness instance;

        public AnalyticsOverviewDataStalenessTests()
        {
            // TODO uncomment below to create an instance of AnalyticsOverviewDataStaleness
            //instance = new AnalyticsOverviewDataStaleness();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsOverviewDataStaleness
        /// </summary>
        [Fact]
        public void AnalyticsOverviewDataStalenessInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsOverviewDataStaleness
            //Assert.IsType<AnalyticsOverviewDataStaleness>(instance);
        }

        /// <summary>
        /// Test the property 'StaleAccountCount'
        /// </summary>
        [Fact]
        public void StaleAccountCountTest()
        {
            // TODO unit test for the property 'StaleAccountCount'
        }

        /// <summary>
        /// Test the property 'SyncTriggered'
        /// </summary>
        [Fact]
        public void SyncTriggeredTest()
        {
            // TODO unit test for the property 'SyncTriggered'
        }
    }
}
