/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.217.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing ChangeCommerceProductTagsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangeCommerceProductTagsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangeCommerceProductTagsRequest
        //private ChangeCommerceProductTagsRequest instance;

        public ChangeCommerceProductTagsRequestTests()
        {
            // TODO uncomment below to create an instance of ChangeCommerceProductTagsRequest
            //instance = new ChangeCommerceProductTagsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangeCommerceProductTagsRequest
        /// </summary>
        [Fact]
        public void ChangeCommerceProductTagsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChangeCommerceProductTagsRequest
            //Assert.IsType<ChangeCommerceProductTagsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'ProductIds'
        /// </summary>
        [Fact]
        public void ProductIdsTest()
        {
            // TODO unit test for the property 'ProductIds'
        }

        /// <summary>
        /// Test the property 'Add'
        /// </summary>
        [Fact]
        public void AddTest()
        {
            // TODO unit test for the property 'Add'
        }

        /// <summary>
        /// Test the property 'Remove'
        /// </summary>
        [Fact]
        public void RemoveTest()
        {
            // TODO unit test for the property 'Remove'
        }
    }
}
