/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.231.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing CommentAutomationLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommentAutomationLogTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommentAutomationLog
        //private CommentAutomationLog instance;

        public CommentAutomationLogTests()
        {
            // TODO uncomment below to create an instance of CommentAutomationLog
            //instance = new CommentAutomationLog();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommentAutomationLog
        /// </summary>
        [Fact]
        public void CommentAutomationLogInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommentAutomationLog
            //Assert.IsType<CommentAutomationLog>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CommentId'
        /// </summary>
        [Fact]
        public void CommentIdTest()
        {
            // TODO unit test for the property 'CommentId'
        }

        /// <summary>
        /// Test the property 'CommenterId'
        /// </summary>
        [Fact]
        public void CommenterIdTest()
        {
            // TODO unit test for the property 'CommenterId'
        }

        /// <summary>
        /// Test the property 'CommenterName'
        /// </summary>
        [Fact]
        public void CommenterNameTest()
        {
            // TODO unit test for the property 'CommenterName'
        }

        /// <summary>
        /// Test the property 'CommenterUsername'
        /// </summary>
        [Fact]
        public void CommenterUsernameTest()
        {
            // TODO unit test for the property 'CommenterUsername'
        }

        /// <summary>
        /// Test the property 'CommentText'
        /// </summary>
        [Fact]
        public void CommentTextTest()
        {
            // TODO unit test for the property 'CommentText'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'AudienceOutcome'
        /// </summary>
        [Fact]
        public void AudienceOutcomeTest()
        {
            // TODO unit test for the property 'AudienceOutcome'
        }

        /// <summary>
        /// Test the property 'GateButtonStatus'
        /// </summary>
        [Fact]
        public void GateButtonStatusTest()
        {
            // TODO unit test for the property 'GateButtonStatus'
        }

        /// <summary>
        /// Test the property 'CommenterIsFollower'
        /// </summary>
        [Fact]
        public void CommenterIsFollowerTest()
        {
            // TODO unit test for the property 'CommenterIsFollower'
        }

        /// <summary>
        /// Test the property 'CommenterFollowerCount'
        /// </summary>
        [Fact]
        public void CommenterFollowerCountTest()
        {
            // TODO unit test for the property 'CommenterFollowerCount'
        }

        /// <summary>
        /// Test the property 'GateResolvedAt'
        /// </summary>
        [Fact]
        public void GateResolvedAtTest()
        {
            // TODO unit test for the property 'GateResolvedAt'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'PlatformError'
        /// </summary>
        [Fact]
        public void PlatformErrorTest()
        {
            // TODO unit test for the property 'PlatformError'
        }

        /// <summary>
        /// Test the property 'PrivateReplyConsumed'
        /// </summary>
        [Fact]
        public void PrivateReplyConsumedTest()
        {
            // TODO unit test for the property 'PrivateReplyConsumed'
        }

        /// <summary>
        /// Test the property 'CommentReplyStatus'
        /// </summary>
        [Fact]
        public void CommentReplyStatusTest()
        {
            // TODO unit test for the property 'CommentReplyStatus'
        }

        /// <summary>
        /// Test the property 'CommentReplyError'
        /// </summary>
        [Fact]
        public void CommentReplyErrorTest()
        {
            // TODO unit test for the property 'CommentReplyError'
        }

        /// <summary>
        /// Test the property 'PublicReplyPostedAt'
        /// </summary>
        [Fact]
        public void PublicReplyPostedAtTest()
        {
            // TODO unit test for the property 'PublicReplyPostedAt'
        }

        /// <summary>
        /// Test the property 'LikeSkipped'
        /// </summary>
        [Fact]
        public void LikeSkippedTest()
        {
            // TODO unit test for the property 'LikeSkipped'
        }

        /// <summary>
        /// Test the property 'HideSkipped'
        /// </summary>
        [Fact]
        public void HideSkippedTest()
        {
            // TODO unit test for the property 'HideSkipped'
        }

        /// <summary>
        /// Test the property 'MediaError'
        /// </summary>
        [Fact]
        public void MediaErrorTest()
        {
            // TODO unit test for the property 'MediaError'
        }

        /// <summary>
        /// Test the property 'NextDueAt'
        /// </summary>
        [Fact]
        public void NextDueAtTest()
        {
            // TODO unit test for the property 'NextDueAt'
        }

        /// <summary>
        /// Test the property 'ClickedAt'
        /// </summary>
        [Fact]
        public void ClickedAtTest()
        {
            // TODO unit test for the property 'ClickedAt'
        }

        /// <summary>
        /// Test the property 'ClickCount'
        /// </summary>
        [Fact]
        public void ClickCountTest()
        {
            // TODO unit test for the property 'ClickCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
