/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing CreateStandaloneAdRequestDynamicCreative
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateStandaloneAdRequestDynamicCreativeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateStandaloneAdRequestDynamicCreative
        //private CreateStandaloneAdRequestDynamicCreative instance;

        public CreateStandaloneAdRequestDynamicCreativeTests()
        {
            // TODO uncomment below to create an instance of CreateStandaloneAdRequestDynamicCreative
            //instance = new CreateStandaloneAdRequestDynamicCreative();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateStandaloneAdRequestDynamicCreative
        /// </summary>
        [Fact]
        public void CreateStandaloneAdRequestDynamicCreativeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateStandaloneAdRequestDynamicCreative
            //Assert.IsType<CreateStandaloneAdRequestDynamicCreative>(instance);
        }

        /// <summary>
        /// Test the property 'ImageUrls'
        /// </summary>
        [Fact]
        public void ImageUrlsTest()
        {
            // TODO unit test for the property 'ImageUrls'
        }

        /// <summary>
        /// Test the property 'Bodies'
        /// </summary>
        [Fact]
        public void BodiesTest()
        {
            // TODO unit test for the property 'Bodies'
        }

        /// <summary>
        /// Test the property 'Titles'
        /// </summary>
        [Fact]
        public void TitlesTest()
        {
            // TODO unit test for the property 'Titles'
        }

        /// <summary>
        /// Test the property 'Descriptions'
        /// </summary>
        [Fact]
        public void DescriptionsTest()
        {
            // TODO unit test for the property 'Descriptions'
        }

        /// <summary>
        /// Test the property 'LinkUrls'
        /// </summary>
        [Fact]
        public void LinkUrlsTest()
        {
            // TODO unit test for the property 'LinkUrls'
        }

        /// <summary>
        /// Test the property 'CallToActionTypes'
        /// </summary>
        [Fact]
        public void CallToActionTypesTest()
        {
            // TODO unit test for the property 'CallToActionTypes'
        }

        /// <summary>
        /// Test the property 'AdFormat'
        /// </summary>
        [Fact]
        public void AdFormatTest()
        {
            // TODO unit test for the property 'AdFormat'
        }
    }
}
