/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePhoneNumberPortInRequestRequirementsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePhoneNumberPortInRequestRequirementsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePhoneNumberPortInRequestRequirementsInner
        //private CreatePhoneNumberPortInRequestRequirementsInner instance;

        public CreatePhoneNumberPortInRequestRequirementsInnerTests()
        {
            // TODO uncomment below to create an instance of CreatePhoneNumberPortInRequestRequirementsInner
            //instance = new CreatePhoneNumberPortInRequestRequirementsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePhoneNumberPortInRequestRequirementsInner
        /// </summary>
        [Fact]
        public void CreatePhoneNumberPortInRequestRequirementsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePhoneNumberPortInRequestRequirementsInner
            //Assert.IsType<CreatePhoneNumberPortInRequestRequirementsInner>(instance);
        }

        /// <summary>
        /// Test the property 'RequirementTypeId'
        /// </summary>
        [Fact]
        public void RequirementTypeIdTest()
        {
            // TODO unit test for the property 'RequirementTypeId'
        }

        /// <summary>
        /// Test the property 'FieldValue'
        /// </summary>
        [Fact]
        public void FieldValueTest()
        {
            // TODO unit test for the property 'FieldValue'
        }
    }
}
