/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing CreateLeadFormRequestQuestionsInnerOptionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateLeadFormRequestQuestionsInnerOptionsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateLeadFormRequestQuestionsInnerOptionsInner
        //private CreateLeadFormRequestQuestionsInnerOptionsInner instance;

        public CreateLeadFormRequestQuestionsInnerOptionsInnerTests()
        {
            // TODO uncomment below to create an instance of CreateLeadFormRequestQuestionsInnerOptionsInner
            //instance = new CreateLeadFormRequestQuestionsInnerOptionsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateLeadFormRequestQuestionsInnerOptionsInner
        /// </summary>
        [Fact]
        public void CreateLeadFormRequestQuestionsInnerOptionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateLeadFormRequestQuestionsInnerOptionsInner
            //Assert.IsType<CreateLeadFormRequestQuestionsInnerOptionsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
