/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing CreateGoogleBusinessMedia200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateGoogleBusinessMedia200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateGoogleBusinessMedia200Response
        //private CreateGoogleBusinessMedia200Response instance;

        public CreateGoogleBusinessMedia200ResponseTests()
        {
            // TODO uncomment below to create an instance of CreateGoogleBusinessMedia200Response
            //instance = new CreateGoogleBusinessMedia200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateGoogleBusinessMedia200Response
        /// </summary>
        [Fact]
        public void CreateGoogleBusinessMedia200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateGoogleBusinessMedia200Response
            //Assert.IsType<CreateGoogleBusinessMedia200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'MediaFormat'
        /// </summary>
        [Fact]
        public void MediaFormatTest()
        {
            // TODO unit test for the property 'MediaFormat'
        }

        /// <summary>
        /// Test the property 'GoogleUrl'
        /// </summary>
        [Fact]
        public void GoogleUrlTest()
        {
            // TODO unit test for the property 'GoogleUrl'
        }
    }
}
