/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing FollowerStatsResponseStatsValueInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FollowerStatsResponseStatsValueInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FollowerStatsResponseStatsValueInner
        //private FollowerStatsResponseStatsValueInner instance;

        public FollowerStatsResponseStatsValueInnerTests()
        {
            // TODO uncomment below to create an instance of FollowerStatsResponseStatsValueInner
            //instance = new FollowerStatsResponseStatsValueInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FollowerStatsResponseStatsValueInner
        /// </summary>
        [Fact]
        public void FollowerStatsResponseStatsValueInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" FollowerStatsResponseStatsValueInner
            //Assert.IsType<FollowerStatsResponseStatsValueInner>(instance);
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'Followers'
        /// </summary>
        [Fact]
        public void FollowersTest()
        {
            // TODO unit test for the property 'Followers'
        }
    }
}
