/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.234.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetAdReview200ResponseReviewPolicyTopicsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAdReview200ResponseReviewPolicyTopicsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAdReview200ResponseReviewPolicyTopicsInner
        //private GetAdReview200ResponseReviewPolicyTopicsInner instance;

        public GetAdReview200ResponseReviewPolicyTopicsInnerTests()
        {
            // TODO uncomment below to create an instance of GetAdReview200ResponseReviewPolicyTopicsInner
            //instance = new GetAdReview200ResponseReviewPolicyTopicsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAdReview200ResponseReviewPolicyTopicsInner
        /// </summary>
        [Fact]
        public void GetAdReview200ResponseReviewPolicyTopicsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAdReview200ResponseReviewPolicyTopicsInner
            //Assert.IsType<GetAdReview200ResponseReviewPolicyTopicsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Fact]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Evidences'
        /// </summary>
        [Fact]
        public void EvidencesTest()
        {
            // TODO unit test for the property 'Evidences'
        }

        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Fact]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
    }
}
