/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetBroadcast200ResponseBroadcast
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetBroadcast200ResponseBroadcastTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetBroadcast200ResponseBroadcast
        //private GetBroadcast200ResponseBroadcast instance;

        public GetBroadcast200ResponseBroadcastTests()
        {
            // TODO uncomment below to create an instance of GetBroadcast200ResponseBroadcast
            //instance = new GetBroadcast200ResponseBroadcast();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetBroadcast200ResponseBroadcast
        /// </summary>
        [Fact]
        public void GetBroadcast200ResponseBroadcastInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetBroadcast200ResponseBroadcast
            //Assert.IsType<GetBroadcast200ResponseBroadcast>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

        /// <summary>
        /// Test the property 'SegmentFilters'
        /// </summary>
        [Fact]
        public void SegmentFiltersTest()
        {
            // TODO unit test for the property 'SegmentFilters'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ScheduledAt'
        /// </summary>
        [Fact]
        public void ScheduledAtTest()
        {
            // TODO unit test for the property 'ScheduledAt'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'RecipientCount'
        /// </summary>
        [Fact]
        public void RecipientCountTest()
        {
            // TODO unit test for the property 'RecipientCount'
        }

        /// <summary>
        /// Test the property 'SentCount'
        /// </summary>
        [Fact]
        public void SentCountTest()
        {
            // TODO unit test for the property 'SentCount'
        }

        /// <summary>
        /// Test the property 'DeliveredCount'
        /// </summary>
        [Fact]
        public void DeliveredCountTest()
        {
            // TODO unit test for the property 'DeliveredCount'
        }

        /// <summary>
        /// Test the property 'ReadCount'
        /// </summary>
        [Fact]
        public void ReadCountTest()
        {
            // TODO unit test for the property 'ReadCount'
        }

        /// <summary>
        /// Test the property 'FailedCount'
        /// </summary>
        [Fact]
        public void FailedCountTest()
        {
            // TODO unit test for the property 'FailedCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
