/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetInboxConversationMessages200ResponseMessagesInnerDeliveryError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetInboxConversationMessages200ResponseMessagesInnerDeliveryErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetInboxConversationMessages200ResponseMessagesInnerDeliveryError
        //private GetInboxConversationMessages200ResponseMessagesInnerDeliveryError instance;

        public GetInboxConversationMessages200ResponseMessagesInnerDeliveryErrorTests()
        {
            // TODO uncomment below to create an instance of GetInboxConversationMessages200ResponseMessagesInnerDeliveryError
            //instance = new GetInboxConversationMessages200ResponseMessagesInnerDeliveryError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetInboxConversationMessages200ResponseMessagesInnerDeliveryError
        /// </summary>
        [Fact]
        public void GetInboxConversationMessages200ResponseMessagesInnerDeliveryErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetInboxConversationMessages200ResponseMessagesInnerDeliveryError
            //Assert.IsType<GetInboxConversationMessages200ResponseMessagesInnerDeliveryError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
