/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetLinkedInPostAnalytics200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetLinkedInPostAnalytics200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetLinkedInPostAnalytics200Response
        //private GetLinkedInPostAnalytics200Response instance;

        public GetLinkedInPostAnalytics200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetLinkedInPostAnalytics200Response
            //instance = new GetLinkedInPostAnalytics200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetLinkedInPostAnalytics200Response
        /// </summary>
        [Fact]
        public void GetLinkedInPostAnalytics200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetLinkedInPostAnalytics200Response
            //Assert.IsType<GetLinkedInPostAnalytics200Response>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'PostUrn'
        /// </summary>
        [Fact]
        public void PostUrnTest()
        {
            // TODO unit test for the property 'PostUrn'
        }

        /// <summary>
        /// Test the property 'Analytics'
        /// </summary>
        [Fact]
        public void AnalyticsTest()
        {
            // TODO unit test for the property 'Analytics'
        }

        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
    }
}
