/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetPostingFrequency200ResponseFrequencyInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPostingFrequency200ResponseFrequencyInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPostingFrequency200ResponseFrequencyInner
        //private GetPostingFrequency200ResponseFrequencyInner instance;

        public GetPostingFrequency200ResponseFrequencyInnerTests()
        {
            // TODO uncomment below to create an instance of GetPostingFrequency200ResponseFrequencyInner
            //instance = new GetPostingFrequency200ResponseFrequencyInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPostingFrequency200ResponseFrequencyInner
        /// </summary>
        [Fact]
        public void GetPostingFrequency200ResponseFrequencyInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPostingFrequency200ResponseFrequencyInner
            //Assert.IsType<GetPostingFrequency200ResponseFrequencyInner>(instance);
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'PostsPerWeek'
        /// </summary>
        [Fact]
        public void PostsPerWeekTest()
        {
            // TODO unit test for the property 'PostsPerWeek'
        }

        /// <summary>
        /// Test the property 'AvgEngagementRate'
        /// </summary>
        [Fact]
        public void AvgEngagementRateTest()
        {
            // TODO unit test for the property 'AvgEngagementRate'
        }

        /// <summary>
        /// Test the property 'AvgEngagement'
        /// </summary>
        [Fact]
        public void AvgEngagementTest()
        {
            // TODO unit test for the property 'AvgEngagement'
        }

        /// <summary>
        /// Test the property 'WeeksCount'
        /// </summary>
        [Fact]
        public void WeeksCountTest()
        {
            // TODO unit test for the property 'WeeksCount'
        }
    }
}
