/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsAppPhoneNumbers200ResponseSandboxTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsAppPhoneNumbers200ResponseSandboxTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsAppPhoneNumbers200ResponseSandboxTemplate
        //private GetWhatsAppPhoneNumbers200ResponseSandboxTemplate instance;

        public GetWhatsAppPhoneNumbers200ResponseSandboxTemplateTests()
        {
            // TODO uncomment below to create an instance of GetWhatsAppPhoneNumbers200ResponseSandboxTemplate
            //instance = new GetWhatsAppPhoneNumbers200ResponseSandboxTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsAppPhoneNumbers200ResponseSandboxTemplate
        /// </summary>
        [Fact]
        public void GetWhatsAppPhoneNumbers200ResponseSandboxTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsAppPhoneNumbers200ResponseSandboxTemplate
            //Assert.IsType<GetWhatsAppPhoneNumbers200ResponseSandboxTemplate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
    }
}
