/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.222.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsAppPricingAnalytics200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsAppPricingAnalytics200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsAppPricingAnalytics200Response
        //private GetWhatsAppPricingAnalytics200Response instance;

        public GetWhatsAppPricingAnalytics200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetWhatsAppPricingAnalytics200Response
            //instance = new GetWhatsAppPricingAnalytics200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsAppPricingAnalytics200Response
        /// </summary>
        [Fact]
        public void GetWhatsAppPricingAnalytics200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsAppPricingAnalytics200Response
            //Assert.IsType<GetWhatsAppPricingAnalytics200Response>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'Granularity'
        /// </summary>
        [Fact]
        public void GranularityTest()
        {
            // TODO unit test for the property 'Granularity'
        }

        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }

        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }

        /// <summary>
        /// Test the property 'DataPoints'
        /// </summary>
        [Fact]
        public void DataPointsTest()
        {
            // TODO unit test for the property 'DataPoints'
        }
    }
}
