/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.155.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing GoogleRecommendation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoogleRecommendationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoogleRecommendation
        //private GoogleRecommendation instance;

        public GoogleRecommendationTests()
        {
            // TODO uncomment below to create an instance of GoogleRecommendation
            //instance = new GoogleRecommendation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoogleRecommendation
        /// </summary>
        [Fact]
        public void GoogleRecommendationInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoogleRecommendation
            //Assert.IsType<GoogleRecommendation>(instance);
        }

        /// <summary>
        /// Test the property 'ResourceName'
        /// </summary>
        [Fact]
        public void ResourceNameTest()
        {
            // TODO unit test for the property 'ResourceName'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Dismissed'
        /// </summary>
        [Fact]
        public void DismissedTest()
        {
            // TODO unit test for the property 'Dismissed'
        }

        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }

        /// <summary>
        /// Test the property 'CampaignIds'
        /// </summary>
        [Fact]
        public void CampaignIdsTest()
        {
            // TODO unit test for the property 'CampaignIds'
        }

        /// <summary>
        /// Test the property 'AdGroupId'
        /// </summary>
        [Fact]
        public void AdGroupIdTest()
        {
            // TODO unit test for the property 'AdGroupId'
        }

        /// <summary>
        /// Test the property 'CampaignBudgetId'
        /// </summary>
        [Fact]
        public void CampaignBudgetIdTest()
        {
            // TODO unit test for the property 'CampaignBudgetId'
        }

        /// <summary>
        /// Test the property 'Impact'
        /// </summary>
        [Fact]
        public void ImpactTest()
        {
            // TODO unit test for the property 'Impact'
        }

        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
    }
}
