/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing ListLeadForms200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListLeadForms200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListLeadForms200Response
        //private ListLeadForms200Response instance;

        public ListLeadForms200ResponseTests()
        {
            // TODO uncomment below to create an instance of ListLeadForms200Response
            //instance = new ListLeadForms200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListLeadForms200Response
        /// </summary>
        [Fact]
        public void ListLeadForms200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListLeadForms200Response
            //Assert.IsType<ListLeadForms200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Forms'
        /// </summary>
        [Fact]
        public void FormsTest()
        {
            // TODO unit test for the property 'Forms'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
    }
}
