/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing ReplaceAdAudienceCompaniesRequestCompaniesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplaceAdAudienceCompaniesRequestCompaniesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplaceAdAudienceCompaniesRequestCompaniesInner
        //private ReplaceAdAudienceCompaniesRequestCompaniesInner instance;

        public ReplaceAdAudienceCompaniesRequestCompaniesInnerTests()
        {
            // TODO uncomment below to create an instance of ReplaceAdAudienceCompaniesRequestCompaniesInner
            //instance = new ReplaceAdAudienceCompaniesRequestCompaniesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplaceAdAudienceCompaniesRequestCompaniesInner
        /// </summary>
        [Fact]
        public void ReplaceAdAudienceCompaniesRequestCompaniesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplaceAdAudienceCompaniesRequestCompaniesInner
            //Assert.IsType<ReplaceAdAudienceCompaniesRequestCompaniesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'LinkedinPageUrl'
        /// </summary>
        [Fact]
        public void LinkedinPageUrlTest()
        {
            // TODO unit test for the property 'LinkedinPageUrl'
        }
    }
}
