/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing ReplyToInboxPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplyToInboxPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplyToInboxPostRequest
        //private ReplyToInboxPostRequest instance;

        public ReplyToInboxPostRequestTests()
        {
            // TODO uncomment below to create an instance of ReplyToInboxPostRequest
            //instance = new ReplyToInboxPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplyToInboxPostRequest
        /// </summary>
        [Fact]
        public void ReplyToInboxPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplyToInboxPostRequest
            //Assert.IsType<ReplyToInboxPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'AttachmentUrl'
        /// </summary>
        [Fact]
        public void AttachmentUrlTest()
        {
            // TODO unit test for the property 'AttachmentUrl'
        }

        /// <summary>
        /// Test the property 'CommentId'
        /// </summary>
        [Fact]
        public void CommentIdTest()
        {
            // TODO unit test for the property 'CommentId'
        }

        /// <summary>
        /// Test the property 'ParentCid'
        /// </summary>
        [Fact]
        public void ParentCidTest()
        {
            // TODO unit test for the property 'ParentCid'
        }

        /// <summary>
        /// Test the property 'RootUri'
        /// </summary>
        [Fact]
        public void RootUriTest()
        {
            // TODO unit test for the property 'RootUri'
        }

        /// <summary>
        /// Test the property 'RootCid'
        /// </summary>
        [Fact]
        public void RootCidTest()
        {
            // TODO unit test for the property 'RootCid'
        }
    }
}
