/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing RespondToPhoneNumberReviewer200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RespondToPhoneNumberReviewer200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RespondToPhoneNumberReviewer200Response
        //private RespondToPhoneNumberReviewer200Response instance;

        public RespondToPhoneNumberReviewer200ResponseTests()
        {
            // TODO uncomment below to create an instance of RespondToPhoneNumberReviewer200Response
            //instance = new RespondToPhoneNumberReviewer200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RespondToPhoneNumberReviewer200Response
        /// </summary>
        [Fact]
        public void RespondToPhoneNumberReviewer200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RespondToPhoneNumberReviewer200Response
            //Assert.IsType<RespondToPhoneNumberReviewer200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Posted'
        /// </summary>
        [Fact]
        public void PostedTest()
        {
            // TODO unit test for the property 'Posted'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'SiblingsResubmitted'
        /// </summary>
        [Fact]
        public void SiblingsResubmittedTest()
        {
            // TODO unit test for the property 'SiblingsResubmitted'
        }
    }
}
