/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing SelectPinterestBoard200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SelectPinterestBoard200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SelectPinterestBoard200Response
        //private SelectPinterestBoard200Response instance;

        public SelectPinterestBoard200ResponseTests()
        {
            // TODO uncomment below to create an instance of SelectPinterestBoard200Response
            //instance = new SelectPinterestBoard200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SelectPinterestBoard200Response
        /// </summary>
        [Fact]
        public void SelectPinterestBoard200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SelectPinterestBoard200Response
            //Assert.IsType<SelectPinterestBoard200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Fact]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
    }
}
