/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing SetWhatsappBusinessUsername200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetWhatsappBusinessUsername200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetWhatsappBusinessUsername200Response
        //private SetWhatsappBusinessUsername200Response instance;

        public SetWhatsappBusinessUsername200ResponseTests()
        {
            // TODO uncomment below to create an instance of SetWhatsappBusinessUsername200Response
            //instance = new SetWhatsappBusinessUsername200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetWhatsappBusinessUsername200Response
        /// </summary>
        [Fact]
        public void SetWhatsappBusinessUsername200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetWhatsappBusinessUsername200Response
            //Assert.IsType<SetWhatsappBusinessUsername200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
