/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing SetWhatsappBusinessUsernameRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetWhatsappBusinessUsernameRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetWhatsappBusinessUsernameRequest
        //private SetWhatsappBusinessUsernameRequest instance;

        public SetWhatsappBusinessUsernameRequestTests()
        {
            // TODO uncomment below to create an instance of SetWhatsappBusinessUsernameRequest
            //instance = new SetWhatsappBusinessUsernameRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetWhatsappBusinessUsernameRequest
        /// </summary>
        [Fact]
        public void SetWhatsappBusinessUsernameRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetWhatsappBusinessUsernameRequest
            //Assert.IsType<SetWhatsappBusinessUsernameRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'TransferAction'
        /// </summary>
        [Fact]
        public void TransferActionTest()
        {
            // TODO unit test for the property 'TransferAction'
        }
    }
}
