/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAdRequestTargetingKeywordsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAdRequestTargetingKeywordsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAdRequestTargetingKeywordsInner
        //private UpdateAdRequestTargetingKeywordsInner instance;

        public UpdateAdRequestTargetingKeywordsInnerTests()
        {
            // TODO uncomment below to create an instance of UpdateAdRequestTargetingKeywordsInner
            //instance = new UpdateAdRequestTargetingKeywordsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAdRequestTargetingKeywordsInner
        /// </summary>
        [Fact]
        public void UpdateAdRequestTargetingKeywordsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAdRequestTargetingKeywordsInner
            //Assert.IsType<UpdateAdRequestTargetingKeywordsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'MatchType'
        /// </summary>
        [Fact]
        public void MatchTypeTest()
        {
            // TODO unit test for the property 'MatchType'
        }
    }
}
