/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAccount200ResponseXCapabilities
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAccount200ResponseXCapabilitiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAccount200ResponseXCapabilities
        //private UpdateAccount200ResponseXCapabilities instance;

        public UpdateAccount200ResponseXCapabilitiesTests()
        {
            // TODO uncomment below to create an instance of UpdateAccount200ResponseXCapabilities
            //instance = new UpdateAccount200ResponseXCapabilities();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAccount200ResponseXCapabilities
        /// </summary>
        [Fact]
        public void UpdateAccount200ResponseXCapabilitiesInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAccount200ResponseXCapabilities
            //Assert.IsType<UpdateAccount200ResponseXCapabilities>(instance);
        }

        /// <summary>
        /// Test the property 'Analytics'
        /// </summary>
        [Fact]
        public void AnalyticsTest()
        {
            // TODO unit test for the property 'Analytics'
        }

        /// <summary>
        /// Test the property 'Inbox'
        /// </summary>
        [Fact]
        public void InboxTest()
        {
            // TODO unit test for the property 'Inbox'
        }
    }
}
