/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateWhatsAppCallingLegacyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateWhatsAppCallingLegacyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateWhatsAppCallingLegacyRequest
        //private UpdateWhatsAppCallingLegacyRequest instance;

        public UpdateWhatsAppCallingLegacyRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateWhatsAppCallingLegacyRequest
            //instance = new UpdateWhatsAppCallingLegacyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateWhatsAppCallingLegacyRequest
        /// </summary>
        [Fact]
        public void UpdateWhatsAppCallingLegacyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateWhatsAppCallingLegacyRequest
            //Assert.IsType<UpdateWhatsAppCallingLegacyRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'ForwardTo'
        /// </summary>
        [Fact]
        public void ForwardToTest()
        {
            // TODO unit test for the property 'ForwardTo'
        }

        /// <summary>
        /// Test the property 'SipAuthUsername'
        /// </summary>
        [Fact]
        public void SipAuthUsernameTest()
        {
            // TODO unit test for the property 'SipAuthUsername'
        }

        /// <summary>
        /// Test the property 'SipAuthPassword'
        /// </summary>
        [Fact]
        public void SipAuthPasswordTest()
        {
            // TODO unit test for the property 'SipAuthPassword'
        }

        /// <summary>
        /// Test the property 'RecordingEnabled'
        /// </summary>
        [Fact]
        public void RecordingEnabledTest()
        {
            // TODO unit test for the property 'RecordingEnabled'
        }

        /// <summary>
        /// Test the property 'CallIconCountries'
        /// </summary>
        [Fact]
        public void CallIconCountriesTest()
        {
            // TODO unit test for the property 'CallIconCountries'
        }

        /// <summary>
        /// Test the property 'MaxCallDurationSeconds'
        /// </summary>
        [Fact]
        public void MaxCallDurationSecondsTest()
        {
            // TODO unit test for the property 'MaxCallDurationSeconds'
        }

        /// <summary>
        /// Test the property 'ForwardCallerId'
        /// </summary>
        [Fact]
        public void ForwardCallerIdTest()
        {
            // TODO unit test for the property 'ForwardCallerId'
        }
    }
}
