/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateBroadcastRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateBroadcastRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateBroadcastRequest
        //private UpdateBroadcastRequest instance;

        public UpdateBroadcastRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateBroadcastRequest
            //instance = new UpdateBroadcastRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateBroadcastRequest
        /// </summary>
        [Fact]
        public void UpdateBroadcastRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateBroadcastRequest
            //Assert.IsType<UpdateBroadcastRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

        /// <summary>
        /// Test the property 'SegmentFilters'
        /// </summary>
        [Fact]
        public void SegmentFiltersTest()
        {
            // TODO unit test for the property 'SegmentFilters'
        }
    }
}
