/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookPayloadCommentComment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookPayloadCommentCommentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookPayloadCommentComment
        //private WebhookPayloadCommentComment instance;

        public WebhookPayloadCommentCommentTests()
        {
            // TODO uncomment below to create an instance of WebhookPayloadCommentComment
            //instance = new WebhookPayloadCommentComment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookPayloadCommentComment
        /// </summary>
        [Fact]
        public void WebhookPayloadCommentCommentInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookPayloadCommentComment
            //Assert.IsType<WebhookPayloadCommentComment>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PostId'
        /// </summary>
        [Fact]
        public void PostIdTest()
        {
            // TODO unit test for the property 'PostId'
        }

        /// <summary>
        /// Test the property 'PlatformPostId'
        /// </summary>
        [Fact]
        public void PlatformPostIdTest()
        {
            // TODO unit test for the property 'PlatformPostId'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'IsReply'
        /// </summary>
        [Fact]
        public void IsReplyTest()
        {
            // TODO unit test for the property 'IsReply'
        }

        /// <summary>
        /// Test the property 'ParentCommentId'
        /// </summary>
        [Fact]
        public void ParentCommentIdTest()
        {
            // TODO unit test for the property 'ParentCommentId'
        }

        /// <summary>
        /// Test the property 'Ad'
        /// </summary>
        [Fact]
        public void AdTest()
        {
            // TODO unit test for the property 'Ad'
        }
    }
}
