/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing XApiPricing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XApiPricingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XApiPricing
        //private XApiPricing instance;

        public XApiPricingTests()
        {
            // TODO uncomment below to create an instance of XApiPricing
            //instance = new XApiPricing();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XApiPricing
        /// </summary>
        [Fact]
        public void XApiPricingInstanceTest()
        {
            // TODO uncomment below to test "IsType" XApiPricing
            //Assert.IsType<XApiPricing>(instance);
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Markup'
        /// </summary>
        [Fact]
        public void MarkupTest()
        {
            // TODO unit test for the property 'Markup'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'LastVerified'
        /// </summary>
        [Fact]
        public void LastVerifiedTest()
        {
            // TODO unit test for the property 'LastVerified'
        }

        /// <summary>
        /// Test the property 'Tiers'
        /// </summary>
        [Fact]
        public void TiersTest()
        {
            // TODO unit test for the property 'Tiers'
        }

        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Fact]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }
    }
}
