/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Zernio.Model;
using Zernio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Zernio.Test.Model
{
    /// <summary>
    ///  Class for testing XArticle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class XArticleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for XArticle
        //private XArticle instance;

        public XArticleTests()
        {
            // TODO uncomment below to create an instance of XArticle
            //instance = new XArticle();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of XArticle
        /// </summary>
        [Fact]
        public void XArticleInstanceTest()
        {
            // TODO uncomment below to test "IsType" XArticle
            //Assert.IsType<XArticle>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'ContentState'
        /// </summary>
        [Fact]
        public void ContentStateTest()
        {
            // TODO unit test for the property 'ContentState'
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'Cover'
        /// </summary>
        [Fact]
        public void CoverTest()
        {
            // TODO unit test for the property 'Cover'
        }
    }
}
