/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Zernio.Client;
using Zernio.Api;
// uncomment below to import models
//using Zernio.Model;

namespace Zernio.Test.Api
{
    /// <summary>
    ///  Class for testing AdAccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdAccountsApiTests : IDisposable
    {
        private AdAccountsApi instance;

        public AdAccountsApiTests()
        {
            instance = new AdAccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdAccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdAccountsApi
            //Assert.IsType<AdAccountsApi>(instance);
        }

        /// <summary>
        /// Test AddAccountCallouts
        /// </summary>
        [Fact]
        public void AddAccountCalloutsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AddAccountCalloutsRequest addAccountCalloutsRequest = null;
            //var response = instance.AddAccountCallouts(addAccountCalloutsRequest);
            //Assert.IsType<AddAccountCallouts201Response>(response);
        }

        /// <summary>
        /// Test CreateAdNegativeKeywordList
        /// </summary>
        [Fact]
        public void CreateAdNegativeKeywordListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateAdNegativeKeywordListRequest createAdNegativeKeywordListRequest = null;
            //var response = instance.CreateAdNegativeKeywordList(createAdNegativeKeywordListRequest);
            //Assert.IsType<CreateAdNegativeKeywordList201Response>(response);
        }

        /// <summary>
        /// Test CreateCustomConversion
        /// </summary>
        [Fact]
        public void CreateCustomConversionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //CreateCustomConversionRequest createCustomConversionRequest = null;
            //var response = instance.CreateCustomConversion(accountId, createCustomConversionRequest);
            //Assert.IsType<CustomConversionResult>(response);
        }

        /// <summary>
        /// Test CreateHighDemandPeriod
        /// </summary>
        [Fact]
        public void CreateHighDemandPeriodTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateHighDemandPeriodRequest createHighDemandPeriodRequest = null;
            //var response = instance.CreateHighDemandPeriod(createHighDemandPeriodRequest);
            //Assert.IsType<CreateHighDemandPeriod201Response>(response);
        }

        /// <summary>
        /// Test CreateValueRuleSet
        /// </summary>
        [Fact]
        public void CreateValueRuleSetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateValueRuleSetRequest createValueRuleSetRequest = null;
            //var response = instance.CreateValueRuleSet(createValueRuleSetRequest);
            //Assert.IsType<CreateValueRuleSet201Response>(response);
        }

        /// <summary>
        /// Test DeleteAdNegativeKeywordList
        /// </summary>
        [Fact]
        public void DeleteAdNegativeKeywordListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string listId = null;
            //string accountId = null;
            //string? customerId = null;
            //string? platform = null;
            //var response = instance.DeleteAdNegativeKeywordList(listId, accountId, customerId, platform);
            //Assert.IsType<DeleteAdNegativeKeywordList200Response>(response);
        }

        /// <summary>
        /// Test DeleteValueRuleSet
        /// </summary>
        [Fact]
        public void DeleteValueRuleSetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string valueRuleSetId = null;
            //string accountId = null;
            //var response = instance.DeleteValueRuleSet(valueRuleSetId, accountId);
            //Assert.IsType<DeleteValueRuleSet200Response>(response);
        }

        /// <summary>
        /// Test GetAdAccountFinance
        /// </summary>
        [Fact]
        public void GetAdAccountFinanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //var response = instance.GetAdAccountFinance(accountId, adAccountId);
            //Assert.IsType<GetAdAccountFinance200Response>(response);
        }

        /// <summary>
        /// Test GetAdComments
        /// </summary>
        [Fact]
        public void GetAdCommentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string adId = null;
            //string? placement = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.GetAdComments(adId, placement, limit, cursor);
            //Assert.IsType<GetAdComments200Response>(response);
        }

        /// <summary>
        /// Test GetAdNegativeKeywordList
        /// </summary>
        [Fact]
        public void GetAdNegativeKeywordListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string listId = null;
            //string accountId = null;
            //string? customerId = null;
            //string? platform = null;
            //var response = instance.GetAdNegativeKeywordList(listId, accountId, customerId, platform);
            //Assert.IsType<GetAdNegativeKeywordList200Response>(response);
        }

        /// <summary>
        /// Test GetAdsActivityLog
        /// </summary>
        [Fact]
        public void GetAdsActivityLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //DateOnly? since = null;
            //DateOnly? until = null;
            //string? objectId = null;
            //int? limit = null;
            //string? after = null;
            //var response = instance.GetAdsActivityLog(accountId, adAccountId, since, until, objectId, limit, after);
            //Assert.IsType<GetAdsActivityLog200Response>(response);
        }

        /// <summary>
        /// Test GetDsaDefaults
        /// </summary>
        [Fact]
        public void GetDsaDefaultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //var response = instance.GetDsaDefaults(accountId, adAccountId);
            //Assert.IsType<UpdateAdAccount200Response>(response);
        }

        /// <summary>
        /// Test GetDsaRecommendations
        /// </summary>
        [Fact]
        public void GetDsaRecommendationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //var response = instance.GetDsaRecommendations(accountId, adAccountId);
            //Assert.IsType<GetDsaRecommendations200Response>(response);
        }

        /// <summary>
        /// Test GetValueRuleSet
        /// </summary>
        [Fact]
        public void GetValueRuleSetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string valueRuleSetId = null;
            //string accountId = null;
            //var response = instance.GetValueRuleSet(valueRuleSetId, accountId);
            //Assert.IsType<GetValueRuleSet200Response>(response);
        }

        /// <summary>
        /// Test ListAccountCallouts
        /// </summary>
        [Fact]
        public void ListAccountCalloutsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string? customerId = null;
            //var response = instance.ListAccountCallouts(accountId, customerId);
            //Assert.IsType<ListAccountCallouts200Response>(response);
        }

        /// <summary>
        /// Test ListAdAccounts
        /// </summary>
        [Fact]
        public void ListAdAccountsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string? adAccountId = null;
            //int? limit = null;
            //var response = instance.ListAdAccounts(accountId, adAccountId, limit);
            //Assert.IsType<ListAdAccounts200Response>(response);
        }

        /// <summary>
        /// Test ListAdLabels
        /// </summary>
        [Fact]
        public void ListAdLabelsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //int? limit = null;
            //string? after = null;
            //var response = instance.ListAdLabels(accountId, adAccountId, limit, after);
            //Assert.IsType<ListAdLabels200Response>(response);
        }

        /// <summary>
        /// Test ListAdNegativeKeywordLists
        /// </summary>
        [Fact]
        public void ListAdNegativeKeywordListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string? customerId = null;
            //string? platform = null;
            //var response = instance.ListAdNegativeKeywordLists(accountId, customerId, platform);
            //Assert.IsType<ListAdNegativeKeywordLists200Response>(response);
        }

        /// <summary>
        /// Test ListAdStudies
        /// </summary>
        [Fact]
        public void ListAdStudiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //string? fields = null;
            //int? limit = null;
            //string? after = null;
            //var response = instance.ListAdStudies(accountId, adAccountId, fields, limit, after);
            //Assert.IsType<ListAdStudies200Response>(response);
        }

        /// <summary>
        /// Test ListAdsBusinessCenters
        /// </summary>
        [Fact]
        public void ListAdsBusinessCentersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ListAdsBusinessCenters(accountId);
            //Assert.IsType<ListAdsBusinessCenters200Response>(response);
        }

        /// <summary>
        /// Test ListCustomConversions
        /// </summary>
        [Fact]
        public void ListCustomConversionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //var response = instance.ListCustomConversions(accountId, adAccountId);
            //Assert.IsType<ListCustomConversions200Response>(response);
        }

        /// <summary>
        /// Test ListHighDemandPeriods
        /// </summary>
        [Fact]
        public void ListHighDemandPeriodsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string? campaignId = null;
            //string? adSetId = null;
            //int? limit = null;
            //string? after = null;
            //var response = instance.ListHighDemandPeriods(accountId, campaignId, adSetId, limit, after);
            //Assert.IsType<ListHighDemandPeriods200Response>(response);
        }

        /// <summary>
        /// Test ListMetaBusinesses
        /// </summary>
        [Fact]
        public void ListMetaBusinessesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //int? limit = null;
            //string? after = null;
            //var response = instance.ListMetaBusinesses(accountId, limit, after);
            //Assert.IsType<ListMetaBusinesses200Response>(response);
        }

        /// <summary>
        /// Test ListValueRuleSets
        /// </summary>
        [Fact]
        public void ListValueRuleSetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string adAccountId = null;
            //int? limit = null;
            //string? after = null;
            //var response = instance.ListValueRuleSets(accountId, adAccountId, limit, after);
            //Assert.IsType<ListValueRuleSets200Response>(response);
        }

        /// <summary>
        /// Test RemoveAccountCallout
        /// </summary>
        [Fact]
        public void RemoveAccountCalloutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RemoveAccountCalloutRequest removeAccountCalloutRequest = null;
            //var response = instance.RemoveAccountCallout(removeAccountCalloutRequest);
            //Assert.IsType<RemoveAccountCallout200Response>(response);
        }

        /// <summary>
        /// Test ReplaceAdNegativeKeywordListKeywords
        /// </summary>
        [Fact]
        public void ReplaceAdNegativeKeywordListKeywordsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string listId = null;
            //ReplaceAdNegativeKeywordListKeywordsRequest replaceAdNegativeKeywordListKeywordsRequest = null;
            //var response = instance.ReplaceAdNegativeKeywordListKeywords(listId, replaceAdNegativeKeywordListKeywordsRequest);
            //Assert.IsType<ReplaceAdNegativeKeywordListKeywords200Response>(response);
        }

        /// <summary>
        /// Test UpdateAdAccount
        /// </summary>
        [Fact]
        public void UpdateAdAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateAdAccountRequest updateAdAccountRequest = null;
            //var response = instance.UpdateAdAccount(updateAdAccountRequest);
            //Assert.IsType<UpdateAdAccount200Response>(response);
        }

        /// <summary>
        /// Test UpdateAdNegativeKeywordList
        /// </summary>
        [Fact]
        public void UpdateAdNegativeKeywordListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string listId = null;
            //UpdateAdNegativeKeywordListRequest updateAdNegativeKeywordListRequest = null;
            //var response = instance.UpdateAdNegativeKeywordList(listId, updateAdNegativeKeywordListRequest);
            //Assert.IsType<UpdateAdNegativeKeywordList200Response>(response);
        }

        /// <summary>
        /// Test UpdateValueRuleSet
        /// </summary>
        [Fact]
        public void UpdateValueRuleSetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string valueRuleSetId = null;
            //UpdateValueRuleSetRequest updateValueRuleSetRequest = null;
            //var response = instance.UpdateValueRuleSet(valueRuleSetId, updateValueRuleSetRequest);
            //Assert.IsType<UpdateValueRuleSet200Response>(response);
        }
    }
}
