/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// AttachNumberToSipTrunkRequest
    /// </summary>
    [DataContract(Name = "attachNumberToSipTrunk_request")]
    public partial class AttachNumberToSipTrunkRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttachNumberToSipTrunkRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AttachNumberToSipTrunkRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AttachNumberToSipTrunkRequest" /> class.
        /// </summary>
        /// <param name="trunkId">SIP trunk ID (from POST /v1/phone-numbers/sip-trunks). (required).</param>
        public AttachNumberToSipTrunkRequest(string trunkId = default)
        {
            // to ensure "trunkId" is required (not null)
            if (trunkId == null)
            {
                throw new ArgumentNullException("trunkId is a required property for AttachNumberToSipTrunkRequest and cannot be null");
            }
            this.TrunkId = trunkId;
        }

        /// <summary>
        /// SIP trunk ID (from POST /v1/phone-numbers/sip-trunks).
        /// </summary>
        /// <value>SIP trunk ID (from POST /v1/phone-numbers/sip-trunks).</value>
        [DataMember(Name = "trunkId", IsRequired = true, EmitDefaultValue = true)]
        public string TrunkId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AttachNumberToSipTrunkRequest {\n");
            sb.Append("  TrunkId: ").Append(TrunkId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
