/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// BusinessAgentWebsite
    /// </summary>
    [DataContract(Name = "BusinessAgentWebsite")]
    public partial class BusinessAgentWebsite : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessAgentWebsite" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BusinessAgentWebsite() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessAgentWebsite" /> class.
        /// </summary>
        /// <param name="url">url (required).</param>
        /// <param name="includedSubDomains">includedSubDomains.</param>
        /// <param name="includedUrlPatterns">Only URLs containing one of these substrings are ingested..</param>
        /// <param name="excludedSubDomains">excludedSubDomains.</param>
        /// <param name="excludedUrlPatterns">excludedUrlPatterns.</param>
        /// <param name="singleUrls">Crawl only these exact pages instead of the whole site..</param>
        /// <param name="id">id (required).</param>
        /// <param name="crawlStatus">not_started, pending, in_progress, completed, completed_no_data or failed (see crawl_error)..</param>
        /// <param name="crawlError">crawlError.</param>
        /// <param name="pagesCrawled">pagesCrawled.</param>
        /// <param name="lastCrawledAt">Unix seconds..</param>
        /// <param name="createdAt">Unix seconds..</param>
        public BusinessAgentWebsite(string url = default, List<string> includedSubDomains = default, List<string> includedUrlPatterns = default, List<string> excludedSubDomains = default, List<string> excludedUrlPatterns = default, List<string> singleUrls = default, string id = default, string crawlStatus = default, string crawlError = default, int pagesCrawled = default, int lastCrawledAt = default, int createdAt = default)
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for BusinessAgentWebsite and cannot be null");
            }
            this.Url = url;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for BusinessAgentWebsite and cannot be null");
            }
            this.Id = id;
            this.IncludedSubDomains = includedSubDomains;
            this.IncludedUrlPatterns = includedUrlPatterns;
            this.ExcludedSubDomains = excludedSubDomains;
            this.ExcludedUrlPatterns = excludedUrlPatterns;
            this.SingleUrls = singleUrls;
            this.CrawlStatus = crawlStatus;
            this.CrawlError = crawlError;
            this.PagesCrawled = pagesCrawled;
            this.LastCrawledAt = lastCrawledAt;
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets IncludedSubDomains
        /// </summary>
        [DataMember(Name = "included_sub_domains", EmitDefaultValue = false)]
        public List<string> IncludedSubDomains { get; set; }

        /// <summary>
        /// Only URLs containing one of these substrings are ingested.
        /// </summary>
        /// <value>Only URLs containing one of these substrings are ingested.</value>
        [DataMember(Name = "included_url_patterns", EmitDefaultValue = false)]
        public List<string> IncludedUrlPatterns { get; set; }

        /// <summary>
        /// Gets or Sets ExcludedSubDomains
        /// </summary>
        [DataMember(Name = "excluded_sub_domains", EmitDefaultValue = false)]
        public List<string> ExcludedSubDomains { get; set; }

        /// <summary>
        /// Gets or Sets ExcludedUrlPatterns
        /// </summary>
        [DataMember(Name = "excluded_url_patterns", EmitDefaultValue = false)]
        public List<string> ExcludedUrlPatterns { get; set; }

        /// <summary>
        /// Crawl only these exact pages instead of the whole site.
        /// </summary>
        /// <value>Crawl only these exact pages instead of the whole site.</value>
        [DataMember(Name = "single_urls", EmitDefaultValue = false)]
        public List<string> SingleUrls { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// not_started, pending, in_progress, completed, completed_no_data or failed (see crawl_error).
        /// </summary>
        /// <value>not_started, pending, in_progress, completed, completed_no_data or failed (see crawl_error).</value>
        [DataMember(Name = "crawl_status", EmitDefaultValue = false)]
        public string CrawlStatus { get; set; }

        /// <summary>
        /// Gets or Sets CrawlError
        /// </summary>
        [DataMember(Name = "crawl_error", EmitDefaultValue = false)]
        public string CrawlError { get; set; }

        /// <summary>
        /// Gets or Sets PagesCrawled
        /// </summary>
        [DataMember(Name = "pages_crawled", EmitDefaultValue = false)]
        public int PagesCrawled { get; set; }

        /// <summary>
        /// Unix seconds.
        /// </summary>
        /// <value>Unix seconds.</value>
        [DataMember(Name = "last_crawled_at", EmitDefaultValue = false)]
        public int LastCrawledAt { get; set; }

        /// <summary>
        /// Unix seconds.
        /// </summary>
        /// <value>Unix seconds.</value>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public int CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BusinessAgentWebsite {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  IncludedSubDomains: ").Append(IncludedSubDomains).Append("\n");
            sb.Append("  IncludedUrlPatterns: ").Append(IncludedUrlPatterns).Append("\n");
            sb.Append("  ExcludedSubDomains: ").Append(ExcludedSubDomains).Append("\n");
            sb.Append("  ExcludedUrlPatterns: ").Append(ExcludedUrlPatterns).Append("\n");
            sb.Append("  SingleUrls: ").Append(SingleUrls).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CrawlStatus: ").Append(CrawlStatus).Append("\n");
            sb.Append("  CrawlError: ").Append(CrawlError).Append("\n");
            sb.Append("  PagesCrawled: ").Append(PagesCrawled).Append("\n");
            sb.Append("  LastCrawledAt: ").Append(LastCrawledAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
