/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// BusinessAgentFaqInput
    /// </summary>
    [DataContract(Name = "BusinessAgentFaqInput")]
    public partial class BusinessAgentFaqInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessAgentFaqInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BusinessAgentFaqInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessAgentFaqInput" /> class.
        /// </summary>
        /// <param name="question">Phrase it the way a customer would ask it; one topic per entry. (required).</param>
        /// <param name="answer">Self-contained; the agent retrieves entries independently. (required).</param>
        /// <param name="metadata">metadata.</param>
        public BusinessAgentFaqInput(string question = default, string answer = default, Dictionary<string, string> metadata = default)
        {
            // to ensure "question" is required (not null)
            if (question == null)
            {
                throw new ArgumentNullException("question is a required property for BusinessAgentFaqInput and cannot be null");
            }
            this.Question = question;
            // to ensure "answer" is required (not null)
            if (answer == null)
            {
                throw new ArgumentNullException("answer is a required property for BusinessAgentFaqInput and cannot be null");
            }
            this.Answer = answer;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Phrase it the way a customer would ask it; one topic per entry.
        /// </summary>
        /// <value>Phrase it the way a customer would ask it; one topic per entry.</value>
        [DataMember(Name = "question", IsRequired = true, EmitDefaultValue = true)]
        public string Question { get; set; }

        /// <summary>
        /// Self-contained; the agent retrieves entries independently.
        /// </summary>
        /// <value>Self-contained; the agent retrieves entries independently.</value>
        [DataMember(Name = "answer", IsRequired = true, EmitDefaultValue = true)]
        public string Answer { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BusinessAgentFaqInput {\n");
            sb.Append("  Question: ").Append(Question).Append("\n");
            sb.Append("  Answer: ").Append(Answer).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Question (string) maxLength
            if (this.Question != null && this.Question.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for Question, length must be less than 1000.", new [] { "Question" });
            }

            // Answer (string) maxLength
            if (this.Answer != null && this.Answer.Length > 8000)
            {
                yield return new ValidationResult("Invalid value for Answer, length must be less than 8000.", new [] { "Answer" });
            }

            yield break;
        }
    }

}
