/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// ConnectSlackChannelRequest
    /// </summary>
    [DataContract(Name = "connectSlackChannel_request")]
    public partial class ConnectSlackChannelRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectSlackChannelRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConnectSlackChannelRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectSlackChannelRequest" /> class.
        /// </summary>
        /// <param name="profileId">profileId (required).</param>
        /// <param name="channelId">Slack channel id, C... or G... (required).</param>
        /// <param name="pendingDataToken">Nonce from the OAuth redirect. Required unless accountId is sent..</param>
        /// <param name="accountId">Existing Slack account whose workspace token is reused. Required unless pendingDataToken is sent..</param>
        public ConnectSlackChannelRequest(string profileId = default, string channelId = default, string pendingDataToken = default, string accountId = default)
        {
            // to ensure "profileId" is required (not null)
            if (profileId == null)
            {
                throw new ArgumentNullException("profileId is a required property for ConnectSlackChannelRequest and cannot be null");
            }
            this.ProfileId = profileId;
            // to ensure "channelId" is required (not null)
            if (channelId == null)
            {
                throw new ArgumentNullException("channelId is a required property for ConnectSlackChannelRequest and cannot be null");
            }
            this.ChannelId = channelId;
            this.PendingDataToken = pendingDataToken;
            this.AccountId = accountId;
        }

        /// <summary>
        /// Gets or Sets ProfileId
        /// </summary>
        [DataMember(Name = "profileId", IsRequired = true, EmitDefaultValue = true)]
        public string ProfileId { get; set; }

        /// <summary>
        /// Slack channel id, C... or G...
        /// </summary>
        /// <value>Slack channel id, C... or G...</value>
        [DataMember(Name = "channelId", IsRequired = true, EmitDefaultValue = true)]
        public string ChannelId { get; set; }

        /// <summary>
        /// Nonce from the OAuth redirect. Required unless accountId is sent.
        /// </summary>
        /// <value>Nonce from the OAuth redirect. Required unless accountId is sent.</value>
        [DataMember(Name = "pendingDataToken", EmitDefaultValue = false)]
        public string PendingDataToken { get; set; }

        /// <summary>
        /// Existing Slack account whose workspace token is reused. Required unless pendingDataToken is sent.
        /// </summary>
        /// <value>Existing Slack account whose workspace token is reused. Required unless pendingDataToken is sent.</value>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectSlackChannelRequest {\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("  PendingDataToken: ").Append(PendingDataToken).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
