/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// CreateAdSetRequest
    /// </summary>
    [DataContract(Name = "createAdSet_request")]
    public partial class CreateAdSetRequest : IValidatableObject
    {
        /// <summary>
        /// Only \&quot;google\&quot; is implemented today; every other value returns 501.
        /// </summary>
        /// <value>Only \&quot;google\&quot; is implemented today; every other value returns 501.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PlatformEnum
        {
            /// <summary>
            /// Enum Facebook for value: facebook
            /// </summary>
            [EnumMember(Value = "facebook")]
            Facebook = 1,

            /// <summary>
            /// Enum Instagram for value: instagram
            /// </summary>
            [EnumMember(Value = "instagram")]
            Instagram = 2,

            /// <summary>
            /// Enum Tiktok for value: tiktok
            /// </summary>
            [EnumMember(Value = "tiktok")]
            Tiktok = 3,

            /// <summary>
            /// Enum Linkedin for value: linkedin
            /// </summary>
            [EnumMember(Value = "linkedin")]
            Linkedin = 4,

            /// <summary>
            /// Enum Pinterest for value: pinterest
            /// </summary>
            [EnumMember(Value = "pinterest")]
            Pinterest = 5,

            /// <summary>
            /// Enum Google for value: google
            /// </summary>
            [EnumMember(Value = "google")]
            Google = 6,

            /// <summary>
            /// Enum Twitter for value: twitter
            /// </summary>
            [EnumMember(Value = "twitter")]
            Twitter = 7,

            /// <summary>
            /// Enum Openai for value: openai
            /// </summary>
            [EnumMember(Value = "openai")]
            Openai = 8
        }


        /// <summary>
        /// Only \&quot;google\&quot; is implemented today; every other value returns 501.
        /// </summary>
        /// <value>Only \&quot;google\&quot; is implemented today; every other value returns 501.</value>
        [DataMember(Name = "platform", IsRequired = true, EmitDefaultValue = true)]
        public PlatformEnum Platform { get; set; }
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum ACTIVE for value: ACTIVE
            /// </summary>
            [EnumMember(Value = "ACTIVE")]
            ACTIVE = 1,

            /// <summary>
            /// Enum PAUSED for value: PAUSED
            /// </summary>
            [EnumMember(Value = "PAUSED")]
            PAUSED = 2
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAdSetRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAdSetRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAdSetRequest" /> class.
        /// </summary>
        /// <param name="accountId">Zernio SocialAccount id owning the Google Ads connection. (required).</param>
        /// <param name="platform">Only \&quot;google\&quot; is implemented today; every other value returns 501. (required).</param>
        /// <param name="campaignId">Google platform campaign ID (numeric) the ad group is created under. (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="status">status (default to StatusEnum.PAUSED).</param>
        /// <param name="customerId">Numeric Google Ads customer id. Only required when the connection has more than one..</param>
        public CreateAdSetRequest(string accountId = default, PlatformEnum platform = default, string campaignId = default, string name = default, StatusEnum? status = StatusEnum.PAUSED, string customerId = default)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for CreateAdSetRequest and cannot be null");
            }
            this.AccountId = accountId;
            this.Platform = platform;
            // to ensure "campaignId" is required (not null)
            if (campaignId == null)
            {
                throw new ArgumentNullException("campaignId is a required property for CreateAdSetRequest and cannot be null");
            }
            this.CampaignId = campaignId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateAdSetRequest and cannot be null");
            }
            this.Name = name;
            this.Status = status;
            this.CustomerId = customerId;
        }

        /// <summary>
        /// Zernio SocialAccount id owning the Google Ads connection.
        /// </summary>
        /// <value>Zernio SocialAccount id owning the Google Ads connection.</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Google platform campaign ID (numeric) the ad group is created under.
        /// </summary>
        /// <value>Google platform campaign ID (numeric) the ad group is created under.</value>
        [DataMember(Name = "campaignId", IsRequired = true, EmitDefaultValue = true)]
        public string CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Numeric Google Ads customer id. Only required when the connection has more than one.
        /// </summary>
        /// <value>Numeric Google Ads customer id. Only required when the connection has more than one.</value>
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAdSetRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
