/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// CreateStandaloneAd200ResponseResultsInner
    /// </summary>
    [DataContract(Name = "createStandaloneAd_200_response_results_inner")]
    public partial class CreateStandaloneAd200ResponseResultsInner : IValidatableObject
    {
        /// <summary>
        /// Defines Node
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NodeEnum
        {
            /// <summary>
            /// Enum Campaign for value: campaign
            /// </summary>
            [EnumMember(Value = "campaign")]
            Campaign = 1,

            /// <summary>
            /// Enum AdSet for value: adSet
            /// </summary>
            [EnumMember(Value = "adSet")]
            AdSet = 2,

            /// <summary>
            /// Enum Creative for value: creative
            /// </summary>
            [EnumMember(Value = "creative")]
            Creative = 3,

            /// <summary>
            /// Enum Ad for value: ad
            /// </summary>
            [EnumMember(Value = "ad")]
            Ad = 4
        }


        /// <summary>
        /// Gets or Sets Node
        /// </summary>
        [DataMember(Name = "node", EmitDefaultValue = false)]
        public NodeEnum? Node { get; set; }
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Validated for value: validated
            /// </summary>
            [EnumMember(Value = "validated")]
            Validated = 1,

            /// <summary>
            /// Enum Skipped for value: skipped
            /// </summary>
            [EnumMember(Value = "skipped")]
            Skipped = 2
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateStandaloneAd200ResponseResultsInner" /> class.
        /// </summary>
        /// <param name="node">node.</param>
        /// <param name="status">status.</param>
        /// <param name="reason">Why the node could not be validated (only on skipped)..</param>
        public CreateStandaloneAd200ResponseResultsInner(NodeEnum? node = default, StatusEnum? status = default, string reason = default)
        {
            this.Node = node;
            this.Status = status;
            this.Reason = reason;
        }

        /// <summary>
        /// Why the node could not be validated (only on skipped).
        /// </summary>
        /// <value>Why the node could not be validated (only on skipped).</value>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateStandaloneAd200ResponseResultsInner {\n");
            sb.Append("  Node: ").Append(Node).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
