/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.59.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// CreateAdCatalogRequest
    /// </summary>
    [DataContract(Name = "createAdCatalog_request")]
    public partial class CreateAdCatalogRequest : IValidatableObject
    {
        /// <summary>
        /// Defines Vertical
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VerticalEnum
        {
            /// <summary>
            /// Enum Commerce for value: commerce
            /// </summary>
            [EnumMember(Value = "commerce")]
            Commerce = 1,

            /// <summary>
            /// Enum Vehicles for value: vehicles
            /// </summary>
            [EnumMember(Value = "vehicles")]
            Vehicles = 2,

            /// <summary>
            /// Enum Hotels for value: hotels
            /// </summary>
            [EnumMember(Value = "hotels")]
            Hotels = 3,

            /// <summary>
            /// Enum Flights for value: flights
            /// </summary>
            [EnumMember(Value = "flights")]
            Flights = 4,

            /// <summary>
            /// Enum Destinations for value: destinations
            /// </summary>
            [EnumMember(Value = "destinations")]
            Destinations = 5,

            /// <summary>
            /// Enum HomeListings for value: home_listings
            /// </summary>
            [EnumMember(Value = "home_listings")]
            HomeListings = 6,

            /// <summary>
            /// Enum LocalServiceBusiness for value: local_service_business
            /// </summary>
            [EnumMember(Value = "local_service_business")]
            LocalServiceBusiness = 7,

            /// <summary>
            /// Enum OfflineCommerce for value: offline_commerce
            /// </summary>
            [EnumMember(Value = "offline_commerce")]
            OfflineCommerce = 8,

            /// <summary>
            /// Enum TicketedExperiences for value: ticketed_experiences
            /// </summary>
            [EnumMember(Value = "ticketed_experiences")]
            TicketedExperiences = 9,

            /// <summary>
            /// Enum TransactableItems for value: transactable_items
            /// </summary>
            [EnumMember(Value = "transactable_items")]
            TransactableItems = 10
        }


        /// <summary>
        /// Gets or Sets Vertical
        /// </summary>
        [DataMember(Name = "vertical", EmitDefaultValue = false)]
        public VerticalEnum? Vertical { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAdCatalogRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAdCatalogRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAdCatalogRequest" /> class.
        /// </summary>
        /// <param name="accountId">A facebook, instagram, metaads or whatsapp account ID (required).</param>
        /// <param name="catalogAccountId">Account whose Meta login token performs the call (see GET).</param>
        /// <param name="adAccountId">Ad account whose owner business creates the catalog.</param>
        /// <param name="businessId">Business portfolio that owns the catalog.</param>
        /// <param name="name">name (required).</param>
        /// <param name="vertical">vertical (default to VerticalEnum.Commerce).</param>
        public CreateAdCatalogRequest(string accountId = default, string catalogAccountId = default, string adAccountId = default, string businessId = default, string name = default, VerticalEnum? vertical = VerticalEnum.Commerce)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for CreateAdCatalogRequest and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateAdCatalogRequest and cannot be null");
            }
            this.Name = name;
            this.CatalogAccountId = catalogAccountId;
            this.AdAccountId = adAccountId;
            this.BusinessId = businessId;
            this.Vertical = vertical;
        }

        /// <summary>
        /// A facebook, instagram, metaads or whatsapp account ID
        /// </summary>
        /// <value>A facebook, instagram, metaads or whatsapp account ID</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Account whose Meta login token performs the call (see GET)
        /// </summary>
        /// <value>Account whose Meta login token performs the call (see GET)</value>
        [DataMember(Name = "catalogAccountId", EmitDefaultValue = false)]
        public string CatalogAccountId { get; set; }

        /// <summary>
        /// Ad account whose owner business creates the catalog
        /// </summary>
        /// <value>Ad account whose owner business creates the catalog</value>
        [DataMember(Name = "adAccountId", EmitDefaultValue = false)]
        public string AdAccountId { get; set; }

        /// <summary>
        /// Business portfolio that owns the catalog
        /// </summary>
        /// <value>Business portfolio that owns the catalog</value>
        [DataMember(Name = "businessId", EmitDefaultValue = false)]
        public string BusinessId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAdCatalogRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  CatalogAccountId: ").Append(CatalogAccountId).Append("\n");
            sb.Append("  AdAccountId: ").Append(AdAccountId).Append("\n");
            sb.Append("  BusinessId: ").Append(BusinessId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Vertical: ").Append(Vertical).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            yield break;
        }
    }

}
