/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// CreateInboxConversationRequest
    /// </summary>
    [DataContract(Name = "createInboxConversation_request")]
    public partial class CreateInboxConversationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateInboxConversationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateInboxConversationRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateInboxConversationRequest" /> class.
        /// </summary>
        /// <param name="accountId">The social account ID to send from (required).</param>
        /// <param name="participantId">Recipient identifier. For X this is the numeric user ID; for WhatsApp, the recipient phone number in international format (digits, country code included). Provide either this or participantUsername..</param>
        /// <param name="participantUsername">Recipient handle/username — an X or Bluesky handle (with or without @) or a Reddit username (with or without u/). Resolved via lookup. Provide either this or participantId..</param>
        /// <param name="message">Text content of the message. At least one of message, attachment, or (for WhatsApp) templateName is required..</param>
        /// <param name="skipDmCheck">X/Twitter only. Skip the receives_your_dm eligibility check before sending. Use if you have already verified the recipient accepts DMs. (default to false).</param>
        /// <param name="templateName">WhatsApp only. Name of the approved template to start the conversation with (required for WhatsApp)..</param>
        /// <param name="templateLanguage">WhatsApp only. Template language code (e.g. en_US)..</param>
        /// <param name="templateParams">WhatsApp only. Body variable values, in order. Works with positional placeholders ({{1}}, {{2}}, ...) and with named placeholders ({{name}}, {{company}} - how Meta Business Manager creates templates), where values fill the named slots in order of appearance..</param>
        public CreateInboxConversationRequest(string accountId = default, string participantId = default, string participantUsername = default, string message = default, bool skipDmCheck = false, string templateName = default, string templateLanguage = default, List<string> templateParams = default)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for CreateInboxConversationRequest and cannot be null");
            }
            this.AccountId = accountId;
            this.ParticipantId = participantId;
            this.ParticipantUsername = participantUsername;
            this.Message = message;
            this.SkipDmCheck = skipDmCheck;
            this.TemplateName = templateName;
            this.TemplateLanguage = templateLanguage;
            this.TemplateParams = templateParams;
        }

        /// <summary>
        /// The social account ID to send from
        /// </summary>
        /// <value>The social account ID to send from</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Recipient identifier. For X this is the numeric user ID; for WhatsApp, the recipient phone number in international format (digits, country code included). Provide either this or participantUsername.
        /// </summary>
        /// <value>Recipient identifier. For X this is the numeric user ID; for WhatsApp, the recipient phone number in international format (digits, country code included). Provide either this or participantUsername.</value>
        [DataMember(Name = "participantId", EmitDefaultValue = false)]
        public string ParticipantId { get; set; }

        /// <summary>
        /// Recipient handle/username — an X or Bluesky handle (with or without @) or a Reddit username (with or without u/). Resolved via lookup. Provide either this or participantId.
        /// </summary>
        /// <value>Recipient handle/username — an X or Bluesky handle (with or without @) or a Reddit username (with or without u/). Resolved via lookup. Provide either this or participantId.</value>
        [DataMember(Name = "participantUsername", EmitDefaultValue = false)]
        public string ParticipantUsername { get; set; }

        /// <summary>
        /// Text content of the message. At least one of message, attachment, or (for WhatsApp) templateName is required.
        /// </summary>
        /// <value>Text content of the message. At least one of message, attachment, or (for WhatsApp) templateName is required.</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// X/Twitter only. Skip the receives_your_dm eligibility check before sending. Use if you have already verified the recipient accepts DMs.
        /// </summary>
        /// <value>X/Twitter only. Skip the receives_your_dm eligibility check before sending. Use if you have already verified the recipient accepts DMs.</value>
        [DataMember(Name = "skipDmCheck", EmitDefaultValue = true)]
        public bool SkipDmCheck { get; set; }

        /// <summary>
        /// WhatsApp only. Name of the approved template to start the conversation with (required for WhatsApp).
        /// </summary>
        /// <value>WhatsApp only. Name of the approved template to start the conversation with (required for WhatsApp).</value>
        [DataMember(Name = "templateName", EmitDefaultValue = false)]
        public string TemplateName { get; set; }

        /// <summary>
        /// WhatsApp only. Template language code (e.g. en_US).
        /// </summary>
        /// <value>WhatsApp only. Template language code (e.g. en_US).</value>
        [DataMember(Name = "templateLanguage", EmitDefaultValue = false)]
        public string TemplateLanguage { get; set; }

        /// <summary>
        /// WhatsApp only. Body variable values, in order. Works with positional placeholders ({{1}}, {{2}}, ...) and with named placeholders ({{name}}, {{company}} - how Meta Business Manager creates templates), where values fill the named slots in order of appearance.
        /// </summary>
        /// <value>WhatsApp only. Body variable values, in order. Works with positional placeholders ({{1}}, {{2}}, ...) and with named placeholders ({{name}}, {{company}} - how Meta Business Manager creates templates), where values fill the named slots in order of appearance.</value>
        [DataMember(Name = "templateParams", EmitDefaultValue = false)]
        public List<string> TemplateParams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateInboxConversationRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  ParticipantId: ").Append(ParticipantId).Append("\n");
            sb.Append("  ParticipantUsername: ").Append(ParticipantUsername).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  SkipDmCheck: ").Append(SkipDmCheck).Append("\n");
            sb.Append("  TemplateName: ").Append(TemplateName).Append("\n");
            sb.Append("  TemplateLanguage: ").Append(TemplateLanguage).Append("\n");
            sb.Append("  TemplateParams: ").Append(TemplateParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
