/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.222.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// GetAdReview200ResponseReview
    /// </summary>
    [DataContract(Name = "getAdReview_200_response_review")]
    public partial class GetAdReview200ResponseReview : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAdReview200ResponseReview" /> class.
        /// </summary>
        /// <param name="approved">TikTok &#x60;is_approved&#x60;..</param>
        /// <param name="reviewStatus">TikTok &#x60;review_status&#x60;, verbatim: ALL_AVAILABLE (approved everywhere), PART_AVAILABLE (approved for part of the targeting), UNAVAILABLE (rejected)..</param>
        /// <param name="forbiddenPlacements">forbiddenPlacements.</param>
        /// <param name="forbiddenAges">forbiddenAges.</param>
        /// <param name="forbiddenLocations">forbiddenLocations.</param>
        /// <param name="forbiddenOperatingSystems">forbiddenOperatingSystems.</param>
        /// <param name="rejections">One entry per rejected piece of content (TikTok &#x60;reject_info&#x60;). Empty when the ad was approved..</param>
        /// <param name="readAt">When the verdict was read from TikTok..</param>
        public GetAdReview200ResponseReview(bool? approved = default, string reviewStatus = default, List<string> forbiddenPlacements = default, List<string> forbiddenAges = default, List<string> forbiddenLocations = default, List<string> forbiddenOperatingSystems = default, List<GetAdReview200ResponseReviewRejectionsInner> rejections = default, DateTime readAt = default)
        {
            this.Approved = approved;
            this.ReviewStatus = reviewStatus;
            this.ForbiddenPlacements = forbiddenPlacements;
            this.ForbiddenAges = forbiddenAges;
            this.ForbiddenLocations = forbiddenLocations;
            this.ForbiddenOperatingSystems = forbiddenOperatingSystems;
            this.Rejections = rejections;
            this.ReadAt = readAt;
        }

        /// <summary>
        /// TikTok &#x60;is_approved&#x60;.
        /// </summary>
        /// <value>TikTok &#x60;is_approved&#x60;.</value>
        [DataMember(Name = "approved", EmitDefaultValue = true)]
        public bool? Approved { get; set; }

        /// <summary>
        /// TikTok &#x60;review_status&#x60;, verbatim: ALL_AVAILABLE (approved everywhere), PART_AVAILABLE (approved for part of the targeting), UNAVAILABLE (rejected).
        /// </summary>
        /// <value>TikTok &#x60;review_status&#x60;, verbatim: ALL_AVAILABLE (approved everywhere), PART_AVAILABLE (approved for part of the targeting), UNAVAILABLE (rejected).</value>
        [DataMember(Name = "reviewStatus", EmitDefaultValue = true)]
        public string ReviewStatus { get; set; }

        /// <summary>
        /// Gets or Sets ForbiddenPlacements
        /// </summary>
        [DataMember(Name = "forbiddenPlacements", EmitDefaultValue = false)]
        public List<string> ForbiddenPlacements { get; set; }

        /// <summary>
        /// Gets or Sets ForbiddenAges
        /// </summary>
        [DataMember(Name = "forbiddenAges", EmitDefaultValue = false)]
        public List<string> ForbiddenAges { get; set; }

        /// <summary>
        /// Gets or Sets ForbiddenLocations
        /// </summary>
        [DataMember(Name = "forbiddenLocations", EmitDefaultValue = false)]
        public List<string> ForbiddenLocations { get; set; }

        /// <summary>
        /// Gets or Sets ForbiddenOperatingSystems
        /// </summary>
        [DataMember(Name = "forbiddenOperatingSystems", EmitDefaultValue = false)]
        public List<string> ForbiddenOperatingSystems { get; set; }

        /// <summary>
        /// One entry per rejected piece of content (TikTok &#x60;reject_info&#x60;). Empty when the ad was approved.
        /// </summary>
        /// <value>One entry per rejected piece of content (TikTok &#x60;reject_info&#x60;). Empty when the ad was approved.</value>
        [DataMember(Name = "rejections", EmitDefaultValue = false)]
        public List<GetAdReview200ResponseReviewRejectionsInner> Rejections { get; set; }

        /// <summary>
        /// When the verdict was read from TikTok.
        /// </summary>
        /// <value>When the verdict was read from TikTok.</value>
        [DataMember(Name = "readAt", EmitDefaultValue = false)]
        public DateTime ReadAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAdReview200ResponseReview {\n");
            sb.Append("  Approved: ").Append(Approved).Append("\n");
            sb.Append("  ReviewStatus: ").Append(ReviewStatus).Append("\n");
            sb.Append("  ForbiddenPlacements: ").Append(ForbiddenPlacements).Append("\n");
            sb.Append("  ForbiddenAges: ").Append(ForbiddenAges).Append("\n");
            sb.Append("  ForbiddenLocations: ").Append(ForbiddenLocations).Append("\n");
            sb.Append("  ForbiddenOperatingSystems: ").Append(ForbiddenOperatingSystems).Append("\n");
            sb.Append("  Rejections: ").Append(Rejections).Append("\n");
            sb.Append("  ReadAt: ").Append(ReadAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
