/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// GetLinkedInBidPricing200Response
    /// </summary>
    [DataContract(Name = "getLinkedInBidPricing_200_response")]
    public partial class GetLinkedInBidPricing200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLinkedInBidPricing200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetLinkedInBidPricing200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLinkedInBidPricing200Response" /> class.
        /// </summary>
        /// <param name="available">available (required).</param>
        /// <param name="pricing">pricing.</param>
        public GetLinkedInBidPricing200Response(bool available = default, GetLinkedInBidPricing200ResponsePricing pricing = default)
        {
            this.Available = available;
            this.Pricing = pricing;
        }

        /// <summary>
        /// Gets or Sets Available
        /// </summary>
        [DataMember(Name = "available", IsRequired = true, EmitDefaultValue = true)]
        public bool Available { get; set; }

        /// <summary>
        /// Gets or Sets Pricing
        /// </summary>
        [DataMember(Name = "pricing", EmitDefaultValue = false)]
        public GetLinkedInBidPricing200ResponsePricing Pricing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetLinkedInBidPricing200Response {\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  Pricing: ").Append(Pricing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
