/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// Full form config — sufficient to duplicate the form via POST /v1/ads/lead-forms.
    /// </summary>
    [DataContract(Name = "getLeadForm_200_response_form")]
    public partial class GetLeadForm200ResponseForm : IValidatableObject
    {
        /// <summary>
        /// ARCHIVED forms can&#39;t receive new leads.
        /// </summary>
        /// <value>ARCHIVED forms can&#39;t receive new leads.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum ACTIVE for value: ACTIVE
            /// </summary>
            [EnumMember(Value = "ACTIVE")]
            ACTIVE = 1,

            /// <summary>
            /// Enum ARCHIVED for value: ARCHIVED
            /// </summary>
            [EnumMember(Value = "ARCHIVED")]
            ARCHIVED = 2
        }


        /// <summary>
        /// ARCHIVED forms can&#39;t receive new leads.
        /// </summary>
        /// <value>ARCHIVED forms can&#39;t receive new leads.</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLeadForm200ResponseForm" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="status">ARCHIVED forms can&#39;t receive new leads..</param>
        /// <param name="locale">locale.</param>
        /// <param name="createdTime">createdTime.</param>
        /// <param name="leadsCount">leadsCount.</param>
        /// <param name="privacyPolicyUrl">privacyPolicyUrl.</param>
        /// <param name="followUpActionUrl">followUpActionUrl.</param>
        /// <param name="questions">questions.</param>
        /// <param name="thankYouPage">thankYouPage.</param>
        /// <param name="contextCard">Intro card shown before the form questions (title, content, button label)..</param>
        public GetLeadForm200ResponseForm(string id = default, string name = default, StatusEnum? status = default, string locale = default, DateTime createdTime = default, int leadsCount = default, string privacyPolicyUrl = default, string followUpActionUrl = default, List<GetLeadForm200ResponseFormQuestionsInner> questions = default, GetLeadForm200ResponseFormThankYouPage thankYouPage = default, Object contextCard = default)
        {
            this.Id = id;
            this.Name = name;
            this.Status = status;
            this.Locale = locale;
            this.CreatedTime = createdTime;
            this.LeadsCount = leadsCount;
            this.PrivacyPolicyUrl = privacyPolicyUrl;
            this.FollowUpActionUrl = followUpActionUrl;
            this.Questions = questions;
            this.ThankYouPage = thankYouPage;
            this.ContextCard = contextCard;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Locale
        /// </summary>
        /*
        <example>EN_US</example>
        */
        [DataMember(Name = "locale", EmitDefaultValue = false)]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or Sets CreatedTime
        /// </summary>
        [DataMember(Name = "created_time", EmitDefaultValue = false)]
        public DateTime CreatedTime { get; set; }

        /// <summary>
        /// Gets or Sets LeadsCount
        /// </summary>
        [DataMember(Name = "leads_count", EmitDefaultValue = false)]
        public int LeadsCount { get; set; }

        /// <summary>
        /// Gets or Sets PrivacyPolicyUrl
        /// </summary>
        [DataMember(Name = "privacy_policy_url", EmitDefaultValue = false)]
        public string PrivacyPolicyUrl { get; set; }

        /// <summary>
        /// Gets or Sets FollowUpActionUrl
        /// </summary>
        [DataMember(Name = "follow_up_action_url", EmitDefaultValue = false)]
        public string FollowUpActionUrl { get; set; }

        /// <summary>
        /// Gets or Sets Questions
        /// </summary>
        [DataMember(Name = "questions", EmitDefaultValue = false)]
        public List<GetLeadForm200ResponseFormQuestionsInner> Questions { get; set; }

        /// <summary>
        /// Gets or Sets ThankYouPage
        /// </summary>
        [DataMember(Name = "thank_you_page", EmitDefaultValue = false)]
        public GetLeadForm200ResponseFormThankYouPage ThankYouPage { get; set; }

        /// <summary>
        /// Intro card shown before the form questions (title, content, button label).
        /// </summary>
        /// <value>Intro card shown before the form questions (title, content, button label).</value>
        [DataMember(Name = "context_card", EmitDefaultValue = false)]
        public Object ContextCard { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetLeadForm200ResponseForm {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  CreatedTime: ").Append(CreatedTime).Append("\n");
            sb.Append("  LeadsCount: ").Append(LeadsCount).Append("\n");
            sb.Append("  PrivacyPolicyUrl: ").Append(PrivacyPolicyUrl).Append("\n");
            sb.Append("  FollowUpActionUrl: ").Append(FollowUpActionUrl).Append("\n");
            sb.Append("  Questions: ").Append(Questions).Append("\n");
            sb.Append("  ThankYouPage: ").Append(ThankYouPage).Append("\n");
            sb.Append("  ContextCard: ").Append(ContextCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
