/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.229.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// GetWhatsAppPricingAnalytics200ResponseDataPointsInner
    /// </summary>
    [DataContract(Name = "getWhatsAppPricingAnalytics_200_response_dataPoints_inner")]
    public partial class GetWhatsAppPricingAnalytics200ResponseDataPointsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWhatsAppPricingAnalytics200ResponseDataPointsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetWhatsAppPricingAnalytics200ResponseDataPointsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWhatsAppPricingAnalytics200ResponseDataPointsInner" /> class.
        /// </summary>
        /// <param name="start">start (required).</param>
        /// <param name="end">end (required).</param>
        /// <param name="phoneNumber">Set when dimensions includes PHONE. (required).</param>
        /// <param name="country">Set when dimensions includes COUNTRY. (required).</param>
        /// <param name="tier">Volume pricing tier. Set when dimensions includes TIER. (required).</param>
        /// <param name="pricingType">Set when dimensions includes PRICING_TYPE. (required).</param>
        /// <param name="pricingCategory">Set when dimensions includes PRICING_CATEGORY. (required).</param>
        /// <param name="volume">Messages delivered. (required).</param>
        /// <param name="cost">Approximate charge, in the currency of the WABA&#39;s payment method. (required).</param>
        public GetWhatsAppPricingAnalytics200ResponseDataPointsInner(DateTime start = default, DateTime end = default, string phoneNumber = default, string country = default, string tier = default, string pricingType = default, string pricingCategory = default, int? volume = default, decimal? cost = default)
        {
            this.Start = start;
            this.End = end;
            // to ensure "phoneNumber" is required (not null)
            if (phoneNumber == null)
            {
                throw new ArgumentNullException("phoneNumber is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.PhoneNumber = phoneNumber;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.Country = country;
            // to ensure "tier" is required (not null)
            if (tier == null)
            {
                throw new ArgumentNullException("tier is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.Tier = tier;
            // to ensure "pricingType" is required (not null)
            if (pricingType == null)
            {
                throw new ArgumentNullException("pricingType is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.PricingType = pricingType;
            // to ensure "pricingCategory" is required (not null)
            if (pricingCategory == null)
            {
                throw new ArgumentNullException("pricingCategory is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.PricingCategory = pricingCategory;
            // to ensure "volume" is required (not null)
            if (volume == null)
            {
                throw new ArgumentNullException("volume is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.Volume = volume;
            // to ensure "cost" is required (not null)
            if (cost == null)
            {
                throw new ArgumentNullException("cost is a required property for GetWhatsAppPricingAnalytics200ResponseDataPointsInner and cannot be null");
            }
            this.Cost = cost;
        }

        /// <summary>
        /// Gets or Sets Start
        /// </summary>
        [DataMember(Name = "start", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Start { get; set; }

        /// <summary>
        /// Gets or Sets End
        /// </summary>
        [DataMember(Name = "end", IsRequired = true, EmitDefaultValue = true)]
        public DateTime End { get; set; }

        /// <summary>
        /// Set when dimensions includes PHONE.
        /// </summary>
        /// <value>Set when dimensions includes PHONE.</value>
        [DataMember(Name = "phoneNumber", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Set when dimensions includes COUNTRY.
        /// </summary>
        /// <value>Set when dimensions includes COUNTRY.</value>
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Volume pricing tier. Set when dimensions includes TIER.
        /// </summary>
        /// <value>Volume pricing tier. Set when dimensions includes TIER.</value>
        [DataMember(Name = "tier", IsRequired = true, EmitDefaultValue = true)]
        public string Tier { get; set; }

        /// <summary>
        /// Set when dimensions includes PRICING_TYPE.
        /// </summary>
        /// <value>Set when dimensions includes PRICING_TYPE.</value>
        [DataMember(Name = "pricingType", IsRequired = true, EmitDefaultValue = true)]
        public string PricingType { get; set; }

        /// <summary>
        /// Set when dimensions includes PRICING_CATEGORY.
        /// </summary>
        /// <value>Set when dimensions includes PRICING_CATEGORY.</value>
        [DataMember(Name = "pricingCategory", IsRequired = true, EmitDefaultValue = true)]
        public string PricingCategory { get; set; }

        /// <summary>
        /// Messages delivered.
        /// </summary>
        /// <value>Messages delivered.</value>
        [DataMember(Name = "volume", IsRequired = true, EmitDefaultValue = true)]
        public int? Volume { get; set; }

        /// <summary>
        /// Approximate charge, in the currency of the WABA&#39;s payment method.
        /// </summary>
        /// <value>Approximate charge, in the currency of the WABA&#39;s payment method.</value>
        [DataMember(Name = "cost", IsRequired = true, EmitDefaultValue = true)]
        public decimal? Cost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWhatsAppPricingAnalytics200ResponseDataPointsInner {\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  PricingType: ").Append(PricingType).Append("\n");
            sb.Append("  PricingCategory: ").Append(PricingCategory).Append("\n");
            sb.Append("  Volume: ").Append(Volume).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
