/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// GetWorkflow200ResponseWorkflow
    /// </summary>
    [DataContract(Name = "getWorkflow_200_response_workflow")]
    public partial class GetWorkflow200ResponseWorkflow : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            [EnumMember(Value = "draft")]
            Draft = 1,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 2,

            /// <summary>
            /// Enum Paused for value: paused
            /// </summary>
            [EnumMember(Value = "paused")]
            Paused = 3
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWorkflow200ResponseWorkflow" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="platform">platform.</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="profileId">profileId.</param>
        /// <param name="status">status.</param>
        /// <param name="entryNodeId">entryNodeId.</param>
        /// <param name="nodes">nodes.</param>
        /// <param name="edges">edges.</param>
        /// <param name="totalStarted">totalStarted.</param>
        /// <param name="totalCompleted">totalCompleted.</param>
        /// <param name="totalExited">totalExited.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public GetWorkflow200ResponseWorkflow(string id = default, string name = default, string description = default, string platform = default, string accountId = default, string profileId = default, StatusEnum? status = default, string entryNodeId = default, List<WorkflowNode> nodes = default, List<WorkflowEdge> edges = default, int totalStarted = default, int totalCompleted = default, int totalExited = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.Platform = platform;
            this.AccountId = accountId;
            this.ProfileId = profileId;
            this.Status = status;
            this.EntryNodeId = entryNodeId;
            this.Nodes = nodes;
            this.Edges = edges;
            this.TotalStarted = totalStarted;
            this.TotalCompleted = totalCompleted;
            this.TotalExited = totalExited;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets ProfileId
        /// </summary>
        [DataMember(Name = "profileId", EmitDefaultValue = false)]
        public string ProfileId { get; set; }

        /// <summary>
        /// Gets or Sets EntryNodeId
        /// </summary>
        [DataMember(Name = "entryNodeId", EmitDefaultValue = false)]
        public string EntryNodeId { get; set; }

        /// <summary>
        /// Gets or Sets Nodes
        /// </summary>
        [DataMember(Name = "nodes", EmitDefaultValue = false)]
        public List<WorkflowNode> Nodes { get; set; }

        /// <summary>
        /// Gets or Sets Edges
        /// </summary>
        [DataMember(Name = "edges", EmitDefaultValue = false)]
        public List<WorkflowEdge> Edges { get; set; }

        /// <summary>
        /// Gets or Sets TotalStarted
        /// </summary>
        [DataMember(Name = "totalStarted", EmitDefaultValue = false)]
        public int TotalStarted { get; set; }

        /// <summary>
        /// Gets or Sets TotalCompleted
        /// </summary>
        [DataMember(Name = "totalCompleted", EmitDefaultValue = false)]
        public int TotalCompleted { get; set; }

        /// <summary>
        /// Gets or Sets TotalExited
        /// </summary>
        [DataMember(Name = "totalExited", EmitDefaultValue = false)]
        public int TotalExited { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWorkflow200ResponseWorkflow {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  EntryNodeId: ").Append(EntryNodeId).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("  Edges: ").Append(Edges).Append("\n");
            sb.Append("  TotalStarted: ").Append(TotalStarted).Append("\n");
            sb.Append("  TotalCompleted: ").Append(TotalCompleted).Append("\n");
            sb.Append("  TotalExited: ").Append(TotalExited).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
