/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// GetWhatsAppNumberRemediation200Response
    /// </summary>
    [DataContract(Name = "getWhatsAppNumberRemediation_200_response")]
    public partial class GetWhatsAppNumberRemediation200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWhatsAppNumberRemediation200Response" /> class.
        /// </summary>
        /// <param name="country">country.</param>
        /// <param name="numberType">numberType.</param>
        /// <param name="declineReason">declineReason.</param>
        /// <param name="fields">Same field shape as GET /v1/whatsapp/phone-numbers/kyc..</param>
        public GetWhatsAppNumberRemediation200Response(string country = default, string numberType = default, string declineReason = default, List<Object> fields = default)
        {
            this.Country = country;
            this.NumberType = numberType;
            this.DeclineReason = declineReason;
            this.Fields = fields;
        }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets NumberType
        /// </summary>
        [DataMember(Name = "numberType", EmitDefaultValue = false)]
        public string NumberType { get; set; }

        /// <summary>
        /// Gets or Sets DeclineReason
        /// </summary>
        [DataMember(Name = "declineReason", EmitDefaultValue = true)]
        public string DeclineReason { get; set; }

        /// <summary>
        /// Same field shape as GET /v1/whatsapp/phone-numbers/kyc.
        /// </summary>
        /// <value>Same field shape as GET /v1/whatsapp/phone-numbers/kyc.</value>
        [DataMember(Name = "fields", EmitDefaultValue = false)]
        public List<Object> Fields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWhatsAppNumberRemediation200Response {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  NumberType: ").Append(NumberType).Append("\n");
            sb.Append("  DeclineReason: ").Append(DeclineReason).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
