/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.104.0
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// ListConversionDestinations200ResponseDestinationsInnerConversionEventsInner
    /// </summary>
    [DataContract(Name = "listConversionDestinations_200_response_destinations_inner_conversionEvents_inner")]
    public partial class ListConversionDestinations200ResponseDestinationsInnerConversionEventsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListConversionDestinations200ResponseDestinationsInnerConversionEventsInner" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="eventType">OpenAI event type, e.g. order_created, lead_created, or custom..</param>
        /// <param name="customEventName">customEventName.</param>
        /// <param name="archived">archived.</param>
        /// <param name="optimizable">Active and standard (not custom). Only these can be a conversions campaign&#39;s optimization event..</param>
        public ListConversionDestinations200ResponseDestinationsInnerConversionEventsInner(string id = default, string name = default, string eventType = default, string customEventName = default, bool archived = default, bool optimizable = default)
        {
            this.Id = id;
            this.Name = name;
            this.EventType = eventType;
            this.CustomEventName = customEventName;
            this.Archived = archived;
            this.Optimizable = optimizable;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// OpenAI event type, e.g. order_created, lead_created, or custom.
        /// </summary>
        /// <value>OpenAI event type, e.g. order_created, lead_created, or custom.</value>
        [DataMember(Name = "eventType", EmitDefaultValue = true)]
        public string EventType { get; set; }

        /// <summary>
        /// Gets or Sets CustomEventName
        /// </summary>
        [DataMember(Name = "customEventName", EmitDefaultValue = true)]
        public string CustomEventName { get; set; }

        /// <summary>
        /// Gets or Sets Archived
        /// </summary>
        [DataMember(Name = "archived", EmitDefaultValue = true)]
        public bool Archived { get; set; }

        /// <summary>
        /// Active and standard (not custom). Only these can be a conversions campaign&#39;s optimization event.
        /// </summary>
        /// <value>Active and standard (not custom). Only these can be a conversions campaign&#39;s optimization event.</value>
        [DataMember(Name = "optimizable", EmitDefaultValue = true)]
        public bool Optimizable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListConversionDestinations200ResponseDestinationsInnerConversionEventsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  CustomEventName: ").Append(CustomEventName).Append("\n");
            sb.Append("  Archived: ").Append(Archived).Append("\n");
            sb.Append("  Optimizable: ").Append(Optimizable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
