/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// ListGoogleBusinessMedia200Response
    /// </summary>
    [DataContract(Name = "listGoogleBusinessMedia_200_response")]
    public partial class ListGoogleBusinessMedia200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListGoogleBusinessMedia200Response" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="locationId">locationId.</param>
        /// <param name="mediaItems">mediaItems.</param>
        /// <param name="nextPageToken">nextPageToken.</param>
        /// <param name="totalMediaItemsCount">totalMediaItemsCount.</param>
        public ListGoogleBusinessMedia200Response(bool success = default, string accountId = default, string locationId = default, List<ListGoogleBusinessMedia200ResponseMediaItemsInner> mediaItems = default, string nextPageToken = default, int totalMediaItemsCount = default)
        {
            this.Success = success;
            this.AccountId = accountId;
            this.LocationId = locationId;
            this.MediaItems = mediaItems;
            this.NextPageToken = nextPageToken;
            this.TotalMediaItemsCount = totalMediaItemsCount;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets LocationId
        /// </summary>
        [DataMember(Name = "locationId", EmitDefaultValue = false)]
        public string LocationId { get; set; }

        /// <summary>
        /// Gets or Sets MediaItems
        /// </summary>
        [DataMember(Name = "mediaItems", EmitDefaultValue = false)]
        public List<ListGoogleBusinessMedia200ResponseMediaItemsInner> MediaItems { get; set; }

        /// <summary>
        /// Gets or Sets NextPageToken
        /// </summary>
        [DataMember(Name = "nextPageToken", EmitDefaultValue = false)]
        public string NextPageToken { get; set; }

        /// <summary>
        /// Gets or Sets TotalMediaItemsCount
        /// </summary>
        [DataMember(Name = "totalMediaItemsCount", EmitDefaultValue = false)]
        public int TotalMediaItemsCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListGoogleBusinessMedia200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  MediaItems: ").Append(MediaItems).Append("\n");
            sb.Append("  NextPageToken: ").Append(NextPageToken).Append("\n");
            sb.Append("  TotalMediaItemsCount: ").Append(TotalMediaItemsCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
