/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// ListLeads200ResponseLeadsInner
    /// </summary>
    [DataContract(Name = "listLeads_200_response_leads_inner")]
    public partial class ListLeads200ResponseLeadsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListLeads200ResponseLeadsInner" /> class.
        /// </summary>
        /// <param name="id">Zernio lead id..</param>
        /// <param name="leadgenId">Meta lead id. On LinkedIn, the leadFormResponse id..</param>
        /// <param name="formId">formId.</param>
        /// <param name="formName">formName.</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="adId">adId.</param>
        /// <param name="adsetId">adsetId.</param>
        /// <param name="campaignId">On LinkedIn, this is the LinkedIn Campaign id, which corresponds to platformAdSetId on GET /v1/ads (LinkedIn&#39;s Campaign Group is Zernio&#39;s campaign)..</param>
        /// <param name="isOrganic">isOrganic.</param>
        /// <param name="createdTime">ISO 8601..</param>
        /// <param name="fields">Question key → answer. On LinkedIn, the key is the lowercased predefinedField, else the question name, else the numeric questionId; multiple-choice values are option labels (unlike Meta, which returns the option key)..</param>
        /// <param name="fieldData">Raw Meta field_data..</param>
        public ListLeads200ResponseLeadsInner(string id = default, string leadgenId = default, string formId = default, string formName = default, string accountId = default, string adId = default, string adsetId = default, string campaignId = default, bool isOrganic = default, string createdTime = default, Dictionary<string, string> fields = default, List<Object> fieldData = default)
        {
            this.Id = id;
            this.LeadgenId = leadgenId;
            this.FormId = formId;
            this.FormName = formName;
            this.AccountId = accountId;
            this.AdId = adId;
            this.AdsetId = adsetId;
            this.CampaignId = campaignId;
            this.IsOrganic = isOrganic;
            this.CreatedTime = createdTime;
            this.Fields = fields;
            this.FieldData = fieldData;
        }

        /// <summary>
        /// Zernio lead id.
        /// </summary>
        /// <value>Zernio lead id.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Meta lead id. On LinkedIn, the leadFormResponse id.
        /// </summary>
        /// <value>Meta lead id. On LinkedIn, the leadFormResponse id.</value>
        [DataMember(Name = "leadgenId", EmitDefaultValue = false)]
        public string LeadgenId { get; set; }

        /// <summary>
        /// Gets or Sets FormId
        /// </summary>
        [DataMember(Name = "formId", EmitDefaultValue = false)]
        public string FormId { get; set; }

        /// <summary>
        /// Gets or Sets FormName
        /// </summary>
        [DataMember(Name = "formName", EmitDefaultValue = true)]
        public string FormName { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets AdId
        /// </summary>
        [DataMember(Name = "adId", EmitDefaultValue = true)]
        public string AdId { get; set; }

        /// <summary>
        /// Gets or Sets AdsetId
        /// </summary>
        [DataMember(Name = "adsetId", EmitDefaultValue = true)]
        public string AdsetId { get; set; }

        /// <summary>
        /// On LinkedIn, this is the LinkedIn Campaign id, which corresponds to platformAdSetId on GET /v1/ads (LinkedIn&#39;s Campaign Group is Zernio&#39;s campaign).
        /// </summary>
        /// <value>On LinkedIn, this is the LinkedIn Campaign id, which corresponds to platformAdSetId on GET /v1/ads (LinkedIn&#39;s Campaign Group is Zernio&#39;s campaign).</value>
        [DataMember(Name = "campaignId", EmitDefaultValue = true)]
        public string CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets IsOrganic
        /// </summary>
        [DataMember(Name = "isOrganic", EmitDefaultValue = true)]
        public bool IsOrganic { get; set; }

        /// <summary>
        /// ISO 8601.
        /// </summary>
        /// <value>ISO 8601.</value>
        [DataMember(Name = "createdTime", EmitDefaultValue = true)]
        public string CreatedTime { get; set; }

        /// <summary>
        /// Question key → answer. On LinkedIn, the key is the lowercased predefinedField, else the question name, else the numeric questionId; multiple-choice values are option labels (unlike Meta, which returns the option key).
        /// </summary>
        /// <value>Question key → answer. On LinkedIn, the key is the lowercased predefinedField, else the question name, else the numeric questionId; multiple-choice values are option labels (unlike Meta, which returns the option key).</value>
        [DataMember(Name = "fields", EmitDefaultValue = false)]
        public Dictionary<string, string> Fields { get; set; }

        /// <summary>
        /// Raw Meta field_data.
        /// </summary>
        /// <value>Raw Meta field_data.</value>
        [DataMember(Name = "fieldData", EmitDefaultValue = false)]
        public List<Object> FieldData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListLeads200ResponseLeadsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LeadgenId: ").Append(LeadgenId).Append("\n");
            sb.Append("  FormId: ").Append(FormId).Append("\n");
            sb.Append("  FormName: ").Append(FormName).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AdId: ").Append(AdId).Append("\n");
            sb.Append("  AdsetId: ").Append(AdsetId).Append("\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  IsOrganic: ").Append(IsOrganic).Append("\n");
            sb.Append("  CreatedTime: ").Append(CreatedTime).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  FieldData: ").Append(FieldData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
