/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// All optional.
    /// </summary>
    [DataContract(Name = "sendInboxMessage_request_interactive_action_oneOf_2_parameters")]
    public partial class SendInboxMessageRequestInteractiveActionOneOf2Parameters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestInteractiveActionOneOf2Parameters" /> class.
        /// </summary>
        /// <param name="displayText">Button label. Defaults to \&quot;Call Now\&quot;..</param>
        /// <param name="ttlMinutes">How long the button stays tappable. Defaults to 10080 (7 days)..</param>
        /// <param name="payload">Arbitrary string echoed back as &#x60;cta_payload&#x60; on the &#x60;calls&#x60; webhook (connect/terminate) for attribution..</param>
        public SendInboxMessageRequestInteractiveActionOneOf2Parameters(string displayText = default, int ttlMinutes = default, string payload = default)
        {
            this.DisplayText = displayText;
            this.TtlMinutes = ttlMinutes;
            this.Payload = payload;
        }

        /// <summary>
        /// Button label. Defaults to \&quot;Call Now\&quot;.
        /// </summary>
        /// <value>Button label. Defaults to \&quot;Call Now\&quot;.</value>
        [DataMember(Name = "display_text", EmitDefaultValue = false)]
        public string DisplayText { get; set; }

        /// <summary>
        /// How long the button stays tappable. Defaults to 10080 (7 days).
        /// </summary>
        /// <value>How long the button stays tappable. Defaults to 10080 (7 days).</value>
        [DataMember(Name = "ttl_minutes", EmitDefaultValue = false)]
        public int TtlMinutes { get; set; }

        /// <summary>
        /// Arbitrary string echoed back as &#x60;cta_payload&#x60; on the &#x60;calls&#x60; webhook (connect/terminate) for attribution.
        /// </summary>
        /// <value>Arbitrary string echoed back as &#x60;cta_payload&#x60; on the &#x60;calls&#x60; webhook (connect/terminate) for attribution.</value>
        [DataMember(Name = "payload", EmitDefaultValue = false)]
        public string Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendInboxMessageRequestInteractiveActionOneOf2Parameters {\n");
            sb.Append("  DisplayText: ").Append(DisplayText).Append("\n");
            sb.Append("  TtlMinutes: ").Append(TtlMinutes).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DisplayText (string) maxLength
            if (this.DisplayText != null && this.DisplayText.Length > 20)
            {
                yield return new ValidationResult("Invalid value for DisplayText, length must be less than 20.", new [] { "DisplayText" });
            }

            // TtlMinutes (int) maximum
            if (this.TtlMinutes > (int)43200)
            {
                yield return new ValidationResult("Invalid value for TtlMinutes, must be a value less than or equal to 43200.", new [] { "TtlMinutes" });
            }

            // TtlMinutes (int) minimum
            if (this.TtlMinutes < (int)1)
            {
                yield return new ValidationResult("Invalid value for TtlMinutes, must be a value greater than or equal to 1.", new [] { "TtlMinutes" });
            }

            // Payload (string) maxLength
            if (this.Payload != null && this.Payload.Length > 512)
            {
                yield return new ValidationResult("Invalid value for Payload, length must be less than 512.", new [] { "Payload" });
            }

            yield break;
        }
    }

}
