/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// SendInboxMessageRequestContactsInnerName
    /// </summary>
    [DataContract(Name = "sendInboxMessage_request_contacts_inner_name")]
    public partial class SendInboxMessageRequestContactsInnerName : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestContactsInnerName" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendInboxMessageRequestContactsInnerName() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestContactsInnerName" /> class.
        /// </summary>
        /// <param name="formattedName">Full display name. (required).</param>
        /// <param name="firstName">firstName.</param>
        /// <param name="lastName">lastName.</param>
        public SendInboxMessageRequestContactsInnerName(string formattedName = default, string firstName = default, string lastName = default)
        {
            // to ensure "formattedName" is required (not null)
            if (formattedName == null)
            {
                throw new ArgumentNullException("formattedName is a required property for SendInboxMessageRequestContactsInnerName and cannot be null");
            }
            this.FormattedName = formattedName;
            this.FirstName = firstName;
            this.LastName = lastName;
        }

        /// <summary>
        /// Full display name.
        /// </summary>
        /// <value>Full display name.</value>
        [DataMember(Name = "formatted_name", IsRequired = true, EmitDefaultValue = true)]
        public string FormattedName { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name = "first_name", EmitDefaultValue = false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [DataMember(Name = "last_name", EmitDefaultValue = false)]
        public string LastName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendInboxMessageRequestContactsInnerName {\n");
            sb.Append("  FormattedName: ").Append(FormattedName).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
