/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// SendInboxMessageRequestTemplateElementsInner
    /// </summary>
    [DataContract(Name = "sendInboxMessage_request_template_elements_inner")]
    public partial class SendInboxMessageRequestTemplateElementsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestTemplateElementsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendInboxMessageRequestTemplateElementsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestTemplateElementsInner" /> class.
        /// </summary>
        /// <param name="title">Element title (max 80 chars) (required).</param>
        /// <param name="subtitle">Element subtitle.</param>
        /// <param name="imageUrl">Element image URL.</param>
        /// <param name="buttons">buttons.</param>
        public SendInboxMessageRequestTemplateElementsInner(string title = default, string subtitle = default, string imageUrl = default, List<SendInboxMessageRequestTemplateElementsInnerButtonsInner> buttons = default)
        {
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for SendInboxMessageRequestTemplateElementsInner and cannot be null");
            }
            this.Title = title;
            this.Subtitle = subtitle;
            this.ImageUrl = imageUrl;
            this.Buttons = buttons;
        }

        /// <summary>
        /// Element title (max 80 chars)
        /// </summary>
        /// <value>Element title (max 80 chars)</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Element subtitle
        /// </summary>
        /// <value>Element subtitle</value>
        [DataMember(Name = "subtitle", EmitDefaultValue = false)]
        public string Subtitle { get; set; }

        /// <summary>
        /// Element image URL
        /// </summary>
        /// <value>Element image URL</value>
        [DataMember(Name = "imageUrl", EmitDefaultValue = false)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Buttons
        /// </summary>
        [DataMember(Name = "buttons", EmitDefaultValue = false)]
        public List<SendInboxMessageRequestTemplateElementsInnerButtonsInner> Buttons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendInboxMessageRequestTemplateElementsInner {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Subtitle: ").Append(Subtitle).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  Buttons: ").Append(Buttons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 80.", new [] { "Title" });
            }

            yield break;
        }
    }

}
