/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner
    /// </summary>
    [DataContract(Name = "sendInboxMessage_request_interactive_action_oneOf_7_sections_inner_product_items_inner")]
    public partial class SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner" /> class.
        /// </summary>
        /// <param name="productRetailerId">Retailer ID (SKU) of the product inside the catalog. (required).</param>
        public SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner(string productRetailerId = default)
        {
            // to ensure "productRetailerId" is required (not null)
            if (productRetailerId == null)
            {
                throw new ArgumentNullException("productRetailerId is a required property for SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner and cannot be null");
            }
            this.ProductRetailerId = productRetailerId;
        }

        /// <summary>
        /// Retailer ID (SKU) of the product inside the catalog.
        /// </summary>
        /// <value>Retailer ID (SKU) of the product inside the catalog.</value>
        [DataMember(Name = "product_retailer_id", IsRequired = true, EmitDefaultValue = true)]
        public string ProductRetailerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendInboxMessageRequestInteractiveActionOneOf7SectionsInnerProductItemsInner {\n");
            sb.Append("  ProductRetailerId: ").Append(ProductRetailerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
