/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.241.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// SetCommercePriceListPricesRequestPricesInner
    /// </summary>
    [DataContract(Name = "setCommercePriceListPrices_request_prices_inner")]
    public partial class SetCommercePriceListPricesRequestPricesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetCommercePriceListPricesRequestPricesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetCommercePriceListPricesRequestPricesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetCommercePriceListPricesRequestPricesInner" /> class.
        /// </summary>
        /// <param name="variantId">variantId (required).</param>
        /// <param name="price">Decimal in the price list currency. (required).</param>
        /// <param name="compareAtPrice">compareAtPrice.</param>
        public SetCommercePriceListPricesRequestPricesInner(string variantId = default, string price = default, string compareAtPrice = default)
        {
            // to ensure "variantId" is required (not null)
            if (variantId == null)
            {
                throw new ArgumentNullException("variantId is a required property for SetCommercePriceListPricesRequestPricesInner and cannot be null");
            }
            this.VariantId = variantId;
            // to ensure "price" is required (not null)
            if (price == null)
            {
                throw new ArgumentNullException("price is a required property for SetCommercePriceListPricesRequestPricesInner and cannot be null");
            }
            this.Price = price;
            this.CompareAtPrice = compareAtPrice;
        }

        /// <summary>
        /// Gets or Sets VariantId
        /// </summary>
        [DataMember(Name = "variantId", IsRequired = true, EmitDefaultValue = true)]
        public string VariantId { get; set; }

        /// <summary>
        /// Decimal in the price list currency.
        /// </summary>
        /// <value>Decimal in the price list currency.</value>
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public string Price { get; set; }

        /// <summary>
        /// Gets or Sets CompareAtPrice
        /// </summary>
        [DataMember(Name = "compareAtPrice", EmitDefaultValue = true)]
        public string CompareAtPrice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetCommercePriceListPricesRequestPricesInner {\n");
            sb.Append("  VariantId: ").Append(VariantId).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  CompareAtPrice: ").Append(CompareAtPrice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
