/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// Meta + TikTok (demographics/interests), Google (keyword and device bid adjustment edits only), and LinkedIn (countries or regions required). Pinterest / X return 501. 
    /// </summary>
    [DataContract(Name = "updateAd_request_targeting")]
    public partial class UpdateAdRequestTargeting : IValidatableObject
    {
        /// <summary>
        /// Meta only. Omit to preserve the existing setting on update. 0 &#x3D; disabled, 1 &#x3D; enabled.
        /// </summary>
        /// <value>Meta only. Omit to preserve the existing setting on update. 0 &#x3D; disabled, 1 &#x3D; enabled.</value>
        public enum AdvantageAudienceEnum
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1
        }


        /// <summary>
        /// Meta only. Omit to preserve the existing setting on update. 0 &#x3D; disabled, 1 &#x3D; enabled.
        /// </summary>
        /// <value>Meta only. Omit to preserve the existing setting on update. 0 &#x3D; disabled, 1 &#x3D; enabled.</value>
        [DataMember(Name = "advantage_audience", EmitDefaultValue = false)]
        public AdvantageAudienceEnum? AdvantageAudience { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateAdRequestTargeting" /> class.
        /// </summary>
        /// <param name="keywords">Google only. The FULL desired set of positive keywords for the entire ad group. Omit to leave positives unchanged; [] removes all positives. Negatives are independent. Entries are strings (BROAD) or { text, matchType } with matchType exact | phrase | broad; an omitted matchType also defaults to BROAD. Matching case-insensitive text AND match type retains the existing criterion ID, status, bid overrides, labels and history without a mutation. A changed text or match type uses remove/create, without transferring the old criterion&#39;s attributes or history. See Google keyword replacement above for an EXACT-to-BROAD example. Mirrored to GET /v1/ads/keywords immediately. .</param>
        /// <param name="negativeKeywords">Google only. The FULL desired set of negative keywords for the entire ad group, independent of positives. Omit to leave negatives unchanged; [] removes all negatives. Uses the same text/match-type identity and preservation contract as keywords above. Strings and objects without matchType default to BROAD, so resending an EXACT or PHRASE negative as a bare string requests a different criterion. Campaign negatives are separate: use /v1/ads/campaigns/{campaignId}/negative-keywords to manage those. .</param>
        /// <param name="devices">Google only. The FULL new set of device criteria for the campaign; devices not listed are excluded. Entries are a device name alone (included, no bid adjustment) or { device, bidModifier }..</param>
        /// <param name="ageMin">ageMin.</param>
        /// <param name="ageMax">ageMax.</param>
        /// <param name="countries">ISO 3166-1 alpha-2 codes. On Google this is the FULL new country set for the campaign (same contract as &#x60;locations&#x60;); on LinkedIn it replaces the campaign&#39;s geo criteria..</param>
        /// <param name="locations">locations.</param>
        /// <param name="languages">Google only. The FULL new language set for the campaign, as Google language codes (ISO 639-1, plus variants such as &#x60;zh_CN&#x60;). An unknown code returns 400..</param>
        /// <param name="interests">Interest objects from /v1/ads/interests. Each must include id and name..</param>
        /// <param name="advantageAudience">Meta only. Omit to preserve the existing setting on update. 0 &#x3D; disabled, 1 &#x3D; enabled..</param>
        public UpdateAdRequestTargeting(List<UpdateAdRequestTargetingKeywordsInner> keywords = default, List<UpdateAdRequestTargetingKeywordsInner> negativeKeywords = default, List<UpdateAdRequestTargetingDevicesInner> devices = default, int ageMin = default, int ageMax = default, List<string> countries = default, UpdateAdRequestTargetingLocations locations = default, List<string> languages = default, List<UpdateAdRequestTargetingInterestsInner> interests = default, AdvantageAudienceEnum? advantageAudience = default)
        {
            this.Keywords = keywords;
            this.NegativeKeywords = negativeKeywords;
            this.Devices = devices;
            this.AgeMin = ageMin;
            this.AgeMax = ageMax;
            this.Countries = countries;
            this.Locations = locations;
            this.Languages = languages;
            this.Interests = interests;
            this.AdvantageAudience = advantageAudience;
        }

        /// <summary>
        /// Google only. The FULL desired set of positive keywords for the entire ad group. Omit to leave positives unchanged; [] removes all positives. Negatives are independent. Entries are strings (BROAD) or { text, matchType } with matchType exact | phrase | broad; an omitted matchType also defaults to BROAD. Matching case-insensitive text AND match type retains the existing criterion ID, status, bid overrides, labels and history without a mutation. A changed text or match type uses remove/create, without transferring the old criterion&#39;s attributes or history. See Google keyword replacement above for an EXACT-to-BROAD example. Mirrored to GET /v1/ads/keywords immediately. 
        /// </summary>
        /// <value>Google only. The FULL desired set of positive keywords for the entire ad group. Omit to leave positives unchanged; [] removes all positives. Negatives are independent. Entries are strings (BROAD) or { text, matchType } with matchType exact | phrase | broad; an omitted matchType also defaults to BROAD. Matching case-insensitive text AND match type retains the existing criterion ID, status, bid overrides, labels and history without a mutation. A changed text or match type uses remove/create, without transferring the old criterion&#39;s attributes or history. See Google keyword replacement above for an EXACT-to-BROAD example. Mirrored to GET /v1/ads/keywords immediately. </value>
        [DataMember(Name = "keywords", EmitDefaultValue = false)]
        public List<UpdateAdRequestTargetingKeywordsInner> Keywords { get; set; }

        /// <summary>
        /// Google only. The FULL desired set of negative keywords for the entire ad group, independent of positives. Omit to leave negatives unchanged; [] removes all negatives. Uses the same text/match-type identity and preservation contract as keywords above. Strings and objects without matchType default to BROAD, so resending an EXACT or PHRASE negative as a bare string requests a different criterion. Campaign negatives are separate: use /v1/ads/campaigns/{campaignId}/negative-keywords to manage those. 
        /// </summary>
        /// <value>Google only. The FULL desired set of negative keywords for the entire ad group, independent of positives. Omit to leave negatives unchanged; [] removes all negatives. Uses the same text/match-type identity and preservation contract as keywords above. Strings and objects without matchType default to BROAD, so resending an EXACT or PHRASE negative as a bare string requests a different criterion. Campaign negatives are separate: use /v1/ads/campaigns/{campaignId}/negative-keywords to manage those. </value>
        [DataMember(Name = "negativeKeywords", EmitDefaultValue = false)]
        public List<UpdateAdRequestTargetingKeywordsInner> NegativeKeywords { get; set; }

        /// <summary>
        /// Google only. The FULL new set of device criteria for the campaign; devices not listed are excluded. Entries are a device name alone (included, no bid adjustment) or { device, bidModifier }.
        /// </summary>
        /// <value>Google only. The FULL new set of device criteria for the campaign; devices not listed are excluded. Entries are a device name alone (included, no bid adjustment) or { device, bidModifier }.</value>
        [DataMember(Name = "devices", EmitDefaultValue = false)]
        public List<UpdateAdRequestTargetingDevicesInner> Devices { get; set; }

        /// <summary>
        /// Gets or Sets AgeMin
        /// </summary>
        [DataMember(Name = "ageMin", EmitDefaultValue = false)]
        public int AgeMin { get; set; }

        /// <summary>
        /// Gets or Sets AgeMax
        /// </summary>
        [DataMember(Name = "ageMax", EmitDefaultValue = false)]
        public int AgeMax { get; set; }

        /// <summary>
        /// ISO 3166-1 alpha-2 codes. On Google this is the FULL new country set for the campaign (same contract as &#x60;locations&#x60;); on LinkedIn it replaces the campaign&#39;s geo criteria.
        /// </summary>
        /// <value>ISO 3166-1 alpha-2 codes. On Google this is the FULL new country set for the campaign (same contract as &#x60;locations&#x60;); on LinkedIn it replaces the campaign&#39;s geo criteria.</value>
        [DataMember(Name = "countries", EmitDefaultValue = false)]
        public List<string> Countries { get; set; }

        /// <summary>
        /// Gets or Sets Locations
        /// </summary>
        [DataMember(Name = "locations", EmitDefaultValue = false)]
        public UpdateAdRequestTargetingLocations Locations { get; set; }

        /// <summary>
        /// Google only. The FULL new language set for the campaign, as Google language codes (ISO 639-1, plus variants such as &#x60;zh_CN&#x60;). An unknown code returns 400.
        /// </summary>
        /// <value>Google only. The FULL new language set for the campaign, as Google language codes (ISO 639-1, plus variants such as &#x60;zh_CN&#x60;). An unknown code returns 400.</value>
        [DataMember(Name = "languages", EmitDefaultValue = false)]
        public List<string> Languages { get; set; }

        /// <summary>
        /// Interest objects from /v1/ads/interests. Each must include id and name.
        /// </summary>
        /// <value>Interest objects from /v1/ads/interests. Each must include id and name.</value>
        [DataMember(Name = "interests", EmitDefaultValue = false)]
        public List<UpdateAdRequestTargetingInterestsInner> Interests { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateAdRequestTargeting {\n");
            sb.Append("  Keywords: ").Append(Keywords).Append("\n");
            sb.Append("  NegativeKeywords: ").Append(NegativeKeywords).Append("\n");
            sb.Append("  Devices: ").Append(Devices).Append("\n");
            sb.Append("  AgeMin: ").Append(AgeMin).Append("\n");
            sb.Append("  AgeMax: ").Append(AgeMax).Append("\n");
            sb.Append("  Countries: ").Append(Countries).Append("\n");
            sb.Append("  Locations: ").Append(Locations).Append("\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("  Interests: ").Append(Interests).Append("\n");
            sb.Append("  AdvantageAudience: ").Append(AdvantageAudience).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AgeMin (int) maximum
            if (this.AgeMin > (int)65)
            {
                yield return new ValidationResult("Invalid value for AgeMin, must be a value less than or equal to 65.", new [] { "AgeMin" });
            }

            // AgeMin (int) minimum
            if (this.AgeMin < (int)13)
            {
                yield return new ValidationResult("Invalid value for AgeMin, must be a value greater than or equal to 13.", new [] { "AgeMin" });
            }

            // AgeMax (int) maximum
            if (this.AgeMax > (int)65)
            {
                yield return new ValidationResult("Invalid value for AgeMax, must be a value less than or equal to 65.", new [] { "AgeMax" });
            }

            // AgeMax (int) minimum
            if (this.AgeMax < (int)13)
            {
                yield return new ValidationResult("Invalid value for AgeMax, must be a value greater than or equal to 13.", new [] { "AgeMax" });
            }

            yield break;
        }
    }

}
