/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// UploadedOrDerivedAudienceMatchRulesInner
    /// </summary>
    [DataContract(Name = "UploadedOrDerivedAudience_matchRules_inner")]
    public partial class UploadedOrDerivedAudienceMatchRulesInner : IValidatableObject
    {
        /// <summary>
        /// Defines MatchType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MatchTypeEnum
        {
            /// <summary>
            /// Enum EXACT for value: EXACT
            /// </summary>
            [EnumMember(Value = "EXACT")]
            EXACT = 1,

            /// <summary>
            /// Enum STARTSWITH for value: STARTS_WITH
            /// </summary>
            [EnumMember(Value = "STARTS_WITH")]
            STARTSWITH = 2,

            /// <summary>
            /// Enum CONTAINS for value: CONTAINS
            /// </summary>
            [EnumMember(Value = "CONTAINS")]
            CONTAINS = 3,

            /// <summary>
            /// Enum ENDSWITH for value: ENDS_WITH
            /// </summary>
            [EnumMember(Value = "ENDS_WITH")]
            ENDSWITH = 4
        }


        /// <summary>
        /// Gets or Sets MatchType
        /// </summary>
        [DataMember(Name = "matchType", IsRequired = true, EmitDefaultValue = true)]
        public MatchTypeEnum MatchType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadedOrDerivedAudienceMatchRulesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UploadedOrDerivedAudienceMatchRulesInner()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadedOrDerivedAudienceMatchRulesInner" /> class.
        /// </summary>
        /// <param name="matchType">matchType (required).</param>
        /// <param name="matchValue">matchValue (required).</param>
        public UploadedOrDerivedAudienceMatchRulesInner(MatchTypeEnum matchType = default, string matchValue = default)
        {
            this.MatchType = matchType;
            // to ensure "matchValue" is required (not null)
            if (matchValue == null)
            {
                throw new ArgumentNullException("matchValue is a required property for UploadedOrDerivedAudienceMatchRulesInner and cannot be null");
            }
            this.MatchValue = matchValue;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets MatchValue
        /// </summary>
        [DataMember(Name = "matchValue", IsRequired = true, EmitDefaultValue = true)]
        public string MatchValue { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UploadedOrDerivedAudienceMatchRulesInner {\n");
            sb.Append("  MatchType: ").Append(MatchType).Append("\n");
            sb.Append("  MatchValue: ").Append(MatchValue).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
