/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// Webhook payload for referral received events (Instagram, Facebook Messenger)
    /// </summary>
    [DataContract(Name = "WebhookPayloadReferral")]
    public partial class WebhookPayloadReferral : IValidatableObject
    {
        /// <summary>
        /// Defines Event
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventEnum
        {
            /// <summary>
            /// Enum ReferralReceived for value: referral.received
            /// </summary>
            [EnumMember(Value = "referral.received")]
            ReferralReceived = 1
        }


        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public EventEnum Event { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookPayloadReferral" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebhookPayloadReferral() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookPayloadReferral" /> class.
        /// </summary>
        /// <param name="id">Stable webhook event ID (required).</param>
        /// <param name="varEvent">varEvent (required).</param>
        /// <param name="referral">referral (required).</param>
        /// <param name="sender">sender (required).</param>
        /// <param name="conversation">conversation (required).</param>
        /// <param name="account">account (required).</param>
        /// <param name="timestamp">UTC time at which Zernio generated this event (set once when the event payload is built, before delivery is queued). Retries and redeliveries keep the original value, so it reflects the event, not the delivery attempt. (required).</param>
        public WebhookPayloadReferral(string id = default, EventEnum varEvent = default, WebhookPayloadReferralReferral referral = default, WebhookPayloadReferralSender sender = default, InboxWebhookConversation conversation = default, InboxWebhookAccount account = default, DateTime timestamp = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WebhookPayloadReferral and cannot be null");
            }
            this.Id = id;
            this.Event = varEvent;
            // to ensure "referral" is required (not null)
            if (referral == null)
            {
                throw new ArgumentNullException("referral is a required property for WebhookPayloadReferral and cannot be null");
            }
            this.Referral = referral;
            // to ensure "sender" is required (not null)
            if (sender == null)
            {
                throw new ArgumentNullException("sender is a required property for WebhookPayloadReferral and cannot be null");
            }
            this.Sender = sender;
            // to ensure "conversation" is required (not null)
            if (conversation == null)
            {
                throw new ArgumentNullException("conversation is a required property for WebhookPayloadReferral and cannot be null");
            }
            this.Conversation = conversation;
            // to ensure "account" is required (not null)
            if (account == null)
            {
                throw new ArgumentNullException("account is a required property for WebhookPayloadReferral and cannot be null");
            }
            this.Account = account;
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// Stable webhook event ID
        /// </summary>
        /// <value>Stable webhook event ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Referral
        /// </summary>
        [DataMember(Name = "referral", IsRequired = true, EmitDefaultValue = true)]
        public WebhookPayloadReferralReferral Referral { get; set; }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [DataMember(Name = "sender", IsRequired = true, EmitDefaultValue = true)]
        public WebhookPayloadReferralSender Sender { get; set; }

        /// <summary>
        /// Gets or Sets Conversation
        /// </summary>
        [DataMember(Name = "conversation", IsRequired = true, EmitDefaultValue = true)]
        public InboxWebhookConversation Conversation { get; set; }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [DataMember(Name = "account", IsRequired = true, EmitDefaultValue = true)]
        public InboxWebhookAccount Account { get; set; }

        /// <summary>
        /// UTC time at which Zernio generated this event (set once when the event payload is built, before delivery is queued). Retries and redeliveries keep the original value, so it reflects the event, not the delivery attempt.
        /// </summary>
        /// <value>UTC time at which Zernio generated this event (set once when the event payload is built, before delivery is queued). Retries and redeliveries keep the original value, so it reflects the event, not the delivery attempt.</value>
        [DataMember(Name = "timestamp", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookPayloadReferral {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Referral: ").Append(Referral).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Conversation: ").Append(Conversation).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
