/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// Individual webhook configuration for receiving real-time notifications
    /// </summary>
    [DataContract(Name = "Webhook")]
    public partial class Webhook : IValidatableObject
    {
        /// <summary>
        /// Defines Events
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventsEnum
        {
            /// <summary>
            /// Enum PostScheduled for value: post.scheduled
            /// </summary>
            [EnumMember(Value = "post.scheduled")]
            PostScheduled = 1,

            /// <summary>
            /// Enum PostPublished for value: post.published
            /// </summary>
            [EnumMember(Value = "post.published")]
            PostPublished = 2,

            /// <summary>
            /// Enum PostFailed for value: post.failed
            /// </summary>
            [EnumMember(Value = "post.failed")]
            PostFailed = 3,

            /// <summary>
            /// Enum PostPartial for value: post.partial
            /// </summary>
            [EnumMember(Value = "post.partial")]
            PostPartial = 4,

            /// <summary>
            /// Enum PostCancelled for value: post.cancelled
            /// </summary>
            [EnumMember(Value = "post.cancelled")]
            PostCancelled = 5,

            /// <summary>
            /// Enum PostRecycled for value: post.recycled
            /// </summary>
            [EnumMember(Value = "post.recycled")]
            PostRecycled = 6,

            /// <summary>
            /// Enum PostPlatformPublished for value: post.platform.published
            /// </summary>
            [EnumMember(Value = "post.platform.published")]
            PostPlatformPublished = 7,

            /// <summary>
            /// Enum PostPlatformFailed for value: post.platform.failed
            /// </summary>
            [EnumMember(Value = "post.platform.failed")]
            PostPlatformFailed = 8,

            /// <summary>
            /// Enum AccountConnected for value: account.connected
            /// </summary>
            [EnumMember(Value = "account.connected")]
            AccountConnected = 9,

            /// <summary>
            /// Enum AccountDisconnected for value: account.disconnected
            /// </summary>
            [EnumMember(Value = "account.disconnected")]
            AccountDisconnected = 10,

            /// <summary>
            /// Enum AccountAdsInitialSyncCompleted for value: account.ads.initial_sync_completed
            /// </summary>
            [EnumMember(Value = "account.ads.initial_sync_completed")]
            AccountAdsInitialSyncCompleted = 11,

            /// <summary>
            /// Enum MessageReceived for value: message.received
            /// </summary>
            [EnumMember(Value = "message.received")]
            MessageReceived = 12,

            /// <summary>
            /// Enum MessageSent for value: message.sent
            /// </summary>
            [EnumMember(Value = "message.sent")]
            MessageSent = 13,

            /// <summary>
            /// Enum MessageEdited for value: message.edited
            /// </summary>
            [EnumMember(Value = "message.edited")]
            MessageEdited = 14,

            /// <summary>
            /// Enum MessageDeleted for value: message.deleted
            /// </summary>
            [EnumMember(Value = "message.deleted")]
            MessageDeleted = 15,

            /// <summary>
            /// Enum MessageDelivered for value: message.delivered
            /// </summary>
            [EnumMember(Value = "message.delivered")]
            MessageDelivered = 16,

            /// <summary>
            /// Enum MessageRead for value: message.read
            /// </summary>
            [EnumMember(Value = "message.read")]
            MessageRead = 17,

            /// <summary>
            /// Enum MessageFailed for value: message.failed
            /// </summary>
            [EnumMember(Value = "message.failed")]
            MessageFailed = 18,

            /// <summary>
            /// Enum ReactionReceived for value: reaction.received
            /// </summary>
            [EnumMember(Value = "reaction.received")]
            ReactionReceived = 19,

            /// <summary>
            /// Enum CommentReceived for value: comment.received
            /// </summary>
            [EnumMember(Value = "comment.received")]
            CommentReceived = 20,

            /// <summary>
            /// Enum ReviewNew for value: review.new
            /// </summary>
            [EnumMember(Value = "review.new")]
            ReviewNew = 21,

            /// <summary>
            /// Enum ReviewUpdated for value: review.updated
            /// </summary>
            [EnumMember(Value = "review.updated")]
            ReviewUpdated = 22,

            /// <summary>
            /// Enum AdStatusChanged for value: ad.status_changed
            /// </summary>
            [EnumMember(Value = "ad.status_changed")]
            AdStatusChanged = 23,

            /// <summary>
            /// Enum WhatsappTemplateStatusUpdated for value: whatsapp.template.status_updated
            /// </summary>
            [EnumMember(Value = "whatsapp.template.status_updated")]
            WhatsappTemplateStatusUpdated = 24,

            /// <summary>
            /// Enum WhatsappNumberActivated for value: whatsapp.number.activated
            /// </summary>
            [EnumMember(Value = "whatsapp.number.activated")]
            WhatsappNumberActivated = 25,

            /// <summary>
            /// Enum WhatsappNumberDeclined for value: whatsapp.number.declined
            /// </summary>
            [EnumMember(Value = "whatsapp.number.declined")]
            WhatsappNumberDeclined = 26,

            /// <summary>
            /// Enum WhatsappNumberVerificationRequired for value: whatsapp.number.verification_required
            /// </summary>
            [EnumMember(Value = "whatsapp.number.verification_required")]
            WhatsappNumberVerificationRequired = 27,

            /// <summary>
            /// Enum WhatsappNumberSuspended for value: whatsapp.number.suspended
            /// </summary>
            [EnumMember(Value = "whatsapp.number.suspended")]
            WhatsappNumberSuspended = 28,

            /// <summary>
            /// Enum WhatsappNumberReactivated for value: whatsapp.number.reactivated
            /// </summary>
            [EnumMember(Value = "whatsapp.number.reactivated")]
            WhatsappNumberReactivated = 29,

            /// <summary>
            /// Enum WhatsappNumberReleased for value: whatsapp.number.released
            /// </summary>
            [EnumMember(Value = "whatsapp.number.released")]
            WhatsappNumberReleased = 30
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Webhook" /> class.
        /// </summary>
        /// <param name="id">Unique webhook identifier.</param>
        /// <param name="name">Webhook name (for identification).</param>
        /// <param name="url">Webhook endpoint URL.</param>
        /// <param name="secret">Secret key for HMAC-SHA256 signature verification..</param>
        /// <param name="events">Events subscribed to.</param>
        /// <param name="isActive">Whether webhook delivery is enabled.</param>
        /// <param name="lastFiredAt">Timestamp of last successful webhook delivery.</param>
        /// <param name="failureCount">Consecutive delivery failures (resets on success, webhook disabled at 10).</param>
        /// <param name="customHeaders">Custom headers included in webhook requests.</param>
        public Webhook(string id = default, string name = default, string url = default, string secret = default, List<EventsEnum> events = default, bool isActive = default, DateTime lastFiredAt = default, int failureCount = default, Dictionary<string, string> customHeaders = default)
        {
            this.Id = id;
            this.Name = name;
            this.Url = url;
            this.Secret = secret;
            this.Events = events;
            this.IsActive = isActive;
            this.LastFiredAt = lastFiredAt;
            this.FailureCount = failureCount;
            this.CustomHeaders = customHeaders;
        }

        /// <summary>
        /// Unique webhook identifier
        /// </summary>
        /// <value>Unique webhook identifier</value>
        [DataMember(Name = "_id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Webhook name (for identification)
        /// </summary>
        /// <value>Webhook name (for identification)</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Webhook endpoint URL
        /// </summary>
        /// <value>Webhook endpoint URL</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Secret key for HMAC-SHA256 signature verification.
        /// </summary>
        /// <value>Secret key for HMAC-SHA256 signature verification.</value>
        [DataMember(Name = "secret", EmitDefaultValue = false)]
        public string Secret { get; set; }

        /// <summary>
        /// Events subscribed to
        /// </summary>
        /// <value>Events subscribed to</value>
        [DataMember(Name = "events", EmitDefaultValue = false)]
        public List<Webhook.EventsEnum> Events { get; set; }

        /// <summary>
        /// Whether webhook delivery is enabled
        /// </summary>
        /// <value>Whether webhook delivery is enabled</value>
        [DataMember(Name = "isActive", EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Timestamp of last successful webhook delivery
        /// </summary>
        /// <value>Timestamp of last successful webhook delivery</value>
        [DataMember(Name = "lastFiredAt", EmitDefaultValue = false)]
        public DateTime LastFiredAt { get; set; }

        /// <summary>
        /// Consecutive delivery failures (resets on success, webhook disabled at 10)
        /// </summary>
        /// <value>Consecutive delivery failures (resets on success, webhook disabled at 10)</value>
        [DataMember(Name = "failureCount", EmitDefaultValue = false)]
        public int FailureCount { get; set; }

        /// <summary>
        /// Custom headers included in webhook requests
        /// </summary>
        /// <value>Custom headers included in webhook requests</value>
        [DataMember(Name = "customHeaders", EmitDefaultValue = false)]
        public Dictionary<string, string> CustomHeaders { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Webhook {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  LastFiredAt: ").Append(LastFiredAt).Append("\n");
            sb.Append("  FailureCount: ").Append(FailureCount).Append("\n");
            sb.Append("  CustomHeaders: ").Append(CustomHeaders).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 50.", new [] { "Name" });
            }

            yield break;
        }
    }

}
