/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing CreateBroadcast200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateBroadcast200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateBroadcast200Response
        //private CreateBroadcast200Response instance;

        public CreateBroadcast200ResponseTests()
        {
            // TODO uncomment below to create an instance of CreateBroadcast200Response
            //instance = new CreateBroadcast200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateBroadcast200Response
        /// </summary>
        [Fact]
        public void CreateBroadcast200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateBroadcast200Response
            //Assert.IsType<CreateBroadcast200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Broadcast'
        /// </summary>
        [Fact]
        public void BroadcastTest()
        {
            // TODO unit test for the property 'Broadcast'
        }
    }
}
