/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetGoogleBusinessPerformance200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetGoogleBusinessPerformance200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetGoogleBusinessPerformance200Response
        //private GetGoogleBusinessPerformance200Response instance;

        public GetGoogleBusinessPerformance200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetGoogleBusinessPerformance200Response
            //instance = new GetGoogleBusinessPerformance200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetGoogleBusinessPerformance200Response
        /// </summary>
        [Fact]
        public void GetGoogleBusinessPerformance200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetGoogleBusinessPerformance200Response
            //Assert.IsType<GetGoogleBusinessPerformance200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'DateRange'
        /// </summary>
        [Fact]
        public void DateRangeTest()
        {
            // TODO unit test for the property 'DateRange'
        }

        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }

        /// <summary>
        /// Test the property 'DataDelay'
        /// </summary>
        [Fact]
        public void DataDelayTest()
        {
            // TODO unit test for the property 'DataDelay'
        }
    }
}
