/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsAppFlowJson200ResponseAssetsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsAppFlowJson200ResponseAssetsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsAppFlowJson200ResponseAssetsInner
        //private GetWhatsAppFlowJson200ResponseAssetsInner instance;

        public GetWhatsAppFlowJson200ResponseAssetsInnerTests()
        {
            // TODO uncomment below to create an instance of GetWhatsAppFlowJson200ResponseAssetsInner
            //instance = new GetWhatsAppFlowJson200ResponseAssetsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsAppFlowJson200ResponseAssetsInner
        /// </summary>
        [Fact]
        public void GetWhatsAppFlowJson200ResponseAssetsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsAppFlowJson200ResponseAssetsInner
            //Assert.IsType<GetWhatsAppFlowJson200ResponseAssetsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'AssetType'
        /// </summary>
        [Fact]
        public void AssetTypeTest()
        {
            // TODO unit test for the property 'AssetType'
        }

        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Fact]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }
    }
}
