/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner
    /// </summary>
    [DataContract(Name = "sendInboxMessage_request_interactive_action_oneOf_sections_inner_rows_inner")]
    public partial class SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner" /> class.
        /// </summary>
        /// <param name="id">Identifier returned in the webhook as metadata.interactiveId (max 200 chars). (required).</param>
        /// <param name="title">Row label (max 24 chars). (required).</param>
        /// <param name="description">Optional description below the title (max 72 chars)..</param>
        public SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner(string id = default, string title = default, string description = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner and cannot be null");
            }
            this.Id = id;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner and cannot be null");
            }
            this.Title = title;
            this.Description = description;
        }

        /// <summary>
        /// Identifier returned in the webhook as metadata.interactiveId (max 200 chars).
        /// </summary>
        /// <value>Identifier returned in the webhook as metadata.interactiveId (max 200 chars).</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Row label (max 24 chars).
        /// </summary>
        /// <value>Row label (max 24 chars).</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Optional description below the title (max 72 chars).
        /// </summary>
        /// <value>Optional description below the title (max 72 chars).</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendInboxMessageRequestInteractiveActionOneOfSectionsInnerRowsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
