/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// A predefined service from Google&#39;s service type catalog
    /// </summary>
    [DataContract(Name = "updateGoogleBusinessLocationDetails_request_serviceItems_inner_structuredServiceItem")]
    public partial class UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerStructuredServiceItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerStructuredServiceItem" /> class.
        /// </summary>
        /// <param name="serviceTypeId">Service type ID from Google&#39;s catalog (e.g. &#39;job_type_id:plumbing_drain_repair&#39;).</param>
        /// <param name="description">Optional description of the service.</param>
        public UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerStructuredServiceItem(string serviceTypeId = default, string description = default)
        {
            this.ServiceTypeId = serviceTypeId;
            this.Description = description;
        }

        /// <summary>
        /// Service type ID from Google&#39;s catalog (e.g. &#39;job_type_id:plumbing_drain_repair&#39;)
        /// </summary>
        /// <value>Service type ID from Google&#39;s catalog (e.g. &#39;job_type_id:plumbing_drain_repair&#39;)</value>
        [DataMember(Name = "serviceTypeId", EmitDefaultValue = false)]
        public string ServiceTypeId { get; set; }

        /// <summary>
        /// Optional description of the service
        /// </summary>
        /// <value>Optional description of the service</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateGoogleBusinessLocationDetailsRequestServiceItemsInnerStructuredServiceItem {\n");
            sb.Append("  ServiceTypeId: ").Append(ServiceTypeId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
